### ISSUE TITLE
Rotate the image does not work properly

### ISSUE THREAD

**Issue by xxalfa** [claviska/SimpleImage#107]
If an image from the camera is rotated, the SimpleImageClass does not recognize it.
If the image is rotated by an image editing program, so it works.

    try
    {
        require_once CORE_DIR . 'SimpleImage.class.php';

        $image = new abeautifulsite\SimpleImage();

        $image->load( $this->ATTACHMENT['tmp_name'][ $FILE_ITEM ] )->thumbnail( 100 )->save( $this->ATTACHMENT['tmp_name'][ $FILE_ITEM ] );
    } 
    catch( Exception $ErrorException )
    {
        $this->LIST_OF_MESSAGES[] = 'Error: ' . $ErrorException->getMessage();
    }

![bild1](https://cloud.githubusercontent.com/assets/15278413/10710751/7965a33c-7a67-11e5-8f2b-85a03eeb3e68.jpg)
![bild2](https://cloud.githubusercontent.com/assets/15278413/10710752/7968e1b4-7a67-11e5-8e25-fc71bf238702.jpg)

**Comment by claviska** [comment]
Look at the auto_orient() method, which rotates based on Exif data.

**Comment by xxalfa** [comment]
I use only one of your examples. SimpleImage/example/index.php:46
I want to create only a preview. Unfortunately I don't know what I have to change.

**Comment by claviska** [comment]
Try:

```php
$image->load( $this->ATTACHMENT['tmp_name'][ $FILE_ITEM ] )->auto_orient()->thumbnail( 100 )->save( $this->ATTACHMENT['tmp_name'][ $FILE_ITEM ] );
```

**Comment by xxalfa** [comment]
It works.
