### ISSUE TITLE
Original JPEG to overlay with PNG does not work

### ISSUE THREAD

**Issue by tetrahydra** [claviska/SimpleImage#108]
I have an original image in multi-format (JPEG, GIF, PNG)

Watermark file is a transparent PNG.

$img1  = new SimpleImage($image_full_path);
$img2 = new SimpleImage(null, 560, 292, '#FFF');
$img2->overlay($img1->best_fit(560, 292), 'center', 1, 0, 0);
$img2->overlay('watermark/background.jpg', 'center', 0.3, 0, 0);

$img1 is a JPEG file.

Result: overlay doesnt show.

**Comment by tetrahydra** [comment]
I just have this problem solved.

The cause for the problem was that, the original PNG image was compressed using tinypng.com therefore, some information must have been lost.

Once I put the original PNG file, the above code works fine.

**Comment by claviska** [comment]
Strange. Not sure what TinyPNG is doing to the image but obviously GD doesn't like it.
