### ISSUE TITLE
exif_read_data .GIF extension "File not supported"

### ISSUE THREAD

**Issue by flacodirt** [claviska/SimpleImage#11]
Trying to load a `.GIF` triggers the following error:

> ```
>        [Warning (PHP)]
>        [Message:]exif_read_data(3.gif) [<a href='function.exif-read-data'>function.exif-read-data</a>]: File not supported
>        [File:]/lib/simpleimage.inc.php
>        [Line:]67
> ```

The `load` method is calling `exif_read_data`, however, this function only works with `JPEG` and `TIFF` according to the manual (http://php.net/manual/en/function.exif-read-data.php).

I didn't see any mention of this in the README or past Issues so I hope I'm not missing something! Seems like it should check for supported file types before trying to load exif data.

**Comment by RRorg** [comment]
Since this comes up on Google when searching for similar errors, a better solution would be to wrap the exif function in a try-catch-block. This will stop the script from crashing even when dealing with a malformed file.

**Comment by localhorst** [comment]
I used:

    'exif' => function_exists('exif_read_data') && @exif_imagetype($this->filename) == 2 ? $this->exif = @exif_read_data($this->filename) : null,

**Comment by kamaroly** [comment]
To enable exif-support configure PHP with **--enable-exif**

Windows users must enable both the `php_mbstring.dll `and `php_exif.dll` DLL's in php.ini. The `php_mbstring.dll` DLL must be loaded before the php_exif.dll DLL so adjust your php.ini accordingly.

Source php documentation : http://php.net/manual/en/exif.installation.php
