### ISSUE TITLE
maxareafill feature

### ISSUE THREAD

**Issue by hellofarhan** [claviska/SimpleImage#112]
I found max area fill feature from this class and it is very useful. 
https://gist.github.com/miguelxt/908143

**Comment by claviska** [comment]
We'd have to code our own or get written permission from the project's owners/contributors to use it due to its GPL licensing.

**Comment by claviska** [comment]
The link above is now pointing to a modified version of SimpleImage. Looking at this now, I'm not sure what the max/min methods you've added are supposed to do.

Closing due to age and lack of demand. If there's a compelling use case, feel free to post more details for consideration :)
