### ISSUE TITLE
Bad crop in thumbnail method on PNG image

### ISSUE THREAD

**Issue by ognistyi** [claviska/SimpleImage#113]
I use 'thumbnail' function and  found strange behavior on some PNG files.

```php
$image->thumbnail(200, 200)->output();
```

For example I try to crete thumbnail of this file - [Original](https://www.dropbox.com/s/aug5wiszmow5s2n/56338ffd1a1da1.84006716.png?dl=0)

And I got - [Result] (https://www.dropbox.com/s/0pcpnfez3uydlq6/56338ffd1a1da1.84006716-thumb.png?dl=0)

Photoshop can't open this, and Dropbox can't generate preview for it.

But in Google Chrome (and OS X Finder) all looks well, except some blank bar at the bottom -
http://prntscr.com/93jayp

And this bar is really problem.

**Comment by claviska** [comment]
> Photoshop can't open this, and Dropbox can't generate preview for it.

Are you seeing this happen with all PNGs or just certain ones? Are they all from the same device? Have they all been PNG-crushed or similar? Any info you can provide will be helpful.

That "bar" looks to be normal spacing. Try setting display:block and it will likely go away.

**Comment by ognistyi** [comment]
I test few PNGs, and before cropping all is great, but when images was cropped, some of this can't be opened in Photoshop. I can visually detect "bad" images by transparent bottom bar. This only affected on PNG images.

upd: No one of cropped PNG images not opened in mozilla FF.

**Comment by claviska** [comment]
Tested with your original image and code:

<img width="480" alt="test-initial" src="https://cloud.githubusercontent.com/assets/55639/11223402/b92e6d8a-8d3d-11e5-993b-9f5cc3da59d2.png">

Which resulted in:

![test-cropped](https://cloud.githubusercontent.com/assets/55639/11223430/e0934f6c-8d3d-11e5-90d0-13640fa62dd5.png)

I tried opening the saved image (via `save()`) and the outputted image (via `output()`). Both worked fine in Photoshop and the browser. I don't see any line or any issues at all.

Are there any other scripts modifying the image? What version of PHP/GD does your server have?

**Comment by ognistyi** [comment]
You are right, all work great!

It's my mistake.
```php
    if (!empty($pattern)) {
        $image->thumbnail($pattern['w'], $pattern['h'])->output();
        // other code
    }
    // other code
    $image->output();
```
The output() method not exit from the script and continue executing, as result I got PNG file with error(text representation) saved at the end of file(headers already sent). 

I'm very sorry for this confuse (
