### ISSUE TITLE
Issues With Cell Phone Photos

### ISSUE THREAD

**Issue by brittonk** [claviska/SimpleImage#116]
I've noticed that auto-orient doesn't work with Samsung Galaxy taken photos, such as the S4. I've also noticed some cell phone users photos get turned to black.

Samsung Galaxy S6 Edge photos also get processed to the wrong orientation.

Are these known issues and is there anyway to patch for these users? Most pictures come in fine.

Thanks.

Here is the code I use for generating the large, medium, and small picture from the uploaded file:

 $image = new abeautifulsite\SimpleImage($target_path . $fileName);

 		$image->auto_orient()->fit_to_width(1024)->overlay('watermarklogoP.png', 'bottom right', .5, -10, -10)->save($target_path . $filenew);
		$image->fit_to_width(335)->save($target_path . $fileMED);
		$image->thumbnail(100)->save($target_path . $fileSM);

**Comment by claviska** [comment]
Possibly related: http://stackoverflow.com/questions/27950755/using-android-camera-api-snapped-photos-orientation-is-always-undefined

Could you supply a few raw photos from the device (one portrait, one landscape, one upside-down portrait, one upside-down landscape) so we can take a look at the EXIF data?

**Comment by brittonk** [comment]
Thanks. Attached are the requested files. I also found this code by following the error link you provided. It may be helpful in patching for Android/Galaxy users. I believe Galaxy is the most used phone in the United States so its a big issue for me to get the orientation working correctly for my users.

http://stackoverflow.com/questions/15808719/controlling-the-camera-to-take-pictures-in-portrait-doesnt-rotate-the-final-ima/26141254#26141254
[galaxys6photos.zip](https://github.com/claviska/SimpleImage/files/76010/galaxys6photos.zip)

**Comment by claviska** [comment]
Just tested with all four images and they get adjusted correctly. Make sure you're calling the `auto_orient()` method and that it's being called on the original image (i.e. the one with the EXIF data).

```php
$img->load('image.jpg')->auto_orient()->output();
```

If you save an image (e.g. after resizing) it will eliminate the EXIF data because the `imagejpeg()` function for GD doesn't support writing it. Thus, subsequent calls to `auto_orient()` will have no effect.

**Comment by claviska** [comment]
It's worth noting that, to save memory and processing time, you can resize an image and adjust the orientation in one call:

```php
// Resize to a specific width/height
$img->load('image.jpg')->resize(320, 240)->auto_orient()->output();

// Resize to a specific width
$img->load('image.jpg')->fit_to_width(320)->auto_orient()->output();

// Resize to a specific height
$img->load('image.jpg')->fit_to_height(240)->auto_orient()->output();
```

**Comment by brittonk** [comment]
Maybe I'm doing something wrong. Here is a simple implementation of your script (my other calls are large/multi-file... but even this one isn't working.

Can you tell me why it would not be auto-orienting with this?

```php

<?

require_once("configlite.php");
include("loginbox.php");
include('js/SimpleImage.php');

	$cookieinfo = preg_replace("/[^a-zA-Z0-9]/", "", $_COOKIE["logged"]);
	$cookieinfo = strtolower($cookieinfo);
	
	$u = preg_replace("/[^a-zA-Z0-9]/", "", $u);
	$u = strtolower($u);

	if (!isset($u)) {
	header("Location: /index1.php?letknown=Member Not Found"); 
			die;	
	} else {
	$u = preg_replace("/[^a-zA-Z0-9]/", "", $u);
	}

if(isset($_FILES['image'])){
    $file_name = $_FILES['image']['name'];
    $file_size =$_FILES['image']['size'];
    $file_tmp =$_FILES['image']['tmp_name'];
    $file_type=$_FILES['image']['type'];
}

$fina = $u . '-' . time();

$extensions = array("jpeg","jpg","png","gif");

$file_ext=strtolower(end(explode('.',$_FILES['image']['name'])));          


    if(in_array($file_ext,$extensions ) === false){
	$errors .= "[file type not allowed]";
	}   
	
	if($file_size > 5242880){
	$errors .= '[file size must be less tham 5 MB]';
	}

	if (empty($errors)==true){
		$uniq = time();

		$img = new abeautifulsite\SimpleImage($file_tmp);
		$img->fit_to_width(640)->overlay('watermarklogoP.png', 'bottom right', .5, -10, -10)->text('sent to ' . $u, 'font.ttf', 12, '#FFFFFF', 'bottom left', 5, -20)->save('imi/' . date("Y") . '/' . $fina . '-MED.jpg');
		$img->fit_to_width(200)->save('imi/' . date("Y") . '/' . $fina . '-SM.jpg');

	}

?>

```

**Comment by brittonk** [comment]
Here is a simple implementation of the SimpleImage script... Can you tell me what I'm doing wrong that is preventing the auto-orient?

Thanks

```php
<?

require_once("configlite.php");
include("loginbox.php");
include('js/SimpleImage.php');

    $cookieinfo = preg_replace("/[^a-zA-Z0-9]/", "", $_COOKIE["logged"]);
    $cookieinfo = strtolower($cookieinfo);

    $u = preg_replace("/[^a-zA-Z0-9]/", "", $u);
    $u = strtolower($u);

    if (!isset($u)) {
    header("Location: /index1.php?letknown=Member Not Found"); 
            die;    
    } else {
    $u = preg_replace("/[^a-zA-Z0-9]/", "", $u);
    }

if(isset($_FILES['image'])){
    $file_name = $_FILES['image']['name'];
    $file_size =$_FILES['image']['size'];
    $file_tmp =$_FILES['image']['tmp_name'];
    $file_type=$_FILES['image']['type'];
}

$fina = $u . '-' . time();

$extensions = array("jpeg","jpg","png","gif");

$file_ext=strtolower(end(explode('.',$_FILES['image']['name'])));          


    if(in_array($file_ext,$extensions ) === false){
    $errors .= "[file type not allowed]";
    }   

    if($file_size > 5242880){
    $errors .= '[file size must be less tham 5 MB]';
    }

    if (empty($errors)==true){
        $uniq = time();

        $img = new abeautifulsite\SimpleImage($file_tmp);
        $img->fit_to_width(640)->overlay('watermarklogoP.png', 'bottom right', .5, -10, -10)->text('sent to ' . $u, 'font.ttf', 12, '#FFFFFF', 'bottom left', 5, -20)->auto_orient()->save('imi/' . date("Y") . '/' . $fina . '-MED.jpg');
        $img->fit_to_width(200)->auto_orient()->save('imi/' . date("Y") . '/' . $fina . '-SM.jpg');

    }

?>
```

**Comment by claviska** [comment]
Looks fine at a glance. If you strip it down to just this and work directly off the images you provided do you see the same results?

```php
$img = new abeautifulsite\SimpleImage('image.jpg');
$img->fit_to_width(640)->auto_orient()->save('image-saved.jpg');
```

That's how I tested it.

**Comment by brittonk** [comment]
Stripped down to those two lines, the image still came out sideways. :(

**Comment by claviska** [comment]
The PHP or GD version won't matter much since rotations are pretty fundamental and the EXIF data comes from [`exif_read_data()`](http://php.net/manual/en/function.exif-read-data.php).

Anyone else having this problem using the sample images posted above?

**Comment by brittonk** [comment]
I have a site with 80,000 users. Whenever I've asked a member who has a sideways picture, they were always taken with a Samsung Galaxy. I saw some closed threads on here (searched before I asked) with someone else saying the auto-orient wasn't working. :(

Do you have any other ideas on what MIGHT interfere with it? I can't imagine why the pictures rotate okay for you and not for me if we're both running the same script. I'm not an expert coder like you so my thoughts on this are...

Is it possible that you opened the files on your computer before trying them on the webserver and some program on windows or other, even a previewer, rewrote the EXIF information to fit its ideal?

**Comment by claviska** [comment]
I just tried again from scratch with those images...same result. They were unzipped in OS X but not modified or re-saved in any way. As far as I know, OS X preserves EXIF data (i.e. it doesn't rewrite it behind the scenes).

I believe Chrome automatically flips images based on their EXIF data, but this shouldn't matter since GD doesn't write EXIF data. Regardless, I tried in multiple browsers and got the same result.

I also tried with the `save()` and `output()` methods—correct results.

I don't doubt that something is causing this to happen to your images, but at the same time I can't confirm that the library is responsible. EXIF orientation handling [used to be a pain](http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/), but I think we've nailed down the closest thing to a standard that's possible.

At this point, I'd suggest making sure that the images being uploaded to your script are retaining their EXIF data. You can do this like so:

```php
$img = new SimpleImage('uploaded-image');
var_dump($img->get_original_info());
```

Ignore the portrait/landscape orientation property, as that's set by SimpleImage based on the image's original width/height. Just look at the EXIF property. If it's missing, that's your problem. Something might be removing it when the image is uploaded (phone's browser, script, etc.).

You can also check your error logs to see if anything strange shows up when you process the images. I doubt it as the operation would likely fail, but it's worth looking at just in case.

**Comment by brittonk** [comment]
It is showing null in the SimpleImage vardump.

I downloaded ExifTool and here are the results for one of the images:

![samsungexif](https://cloud.githubusercontent.com/assets/141741/12131225/657289c8-b3d6-11e5-9625-81d6513e598e.jpg)

**Comment by brittonk** [comment]
Can you confirm that your copy of SimpleImage's create function is the same as mine:

```php
    function create($width, $height = null, $color = null) {

        $height = $height ?: $width;
        $this->width = $width;
        $this->height = $height;
        $this->image = imagecreatetruecolor($width, $height);
        $this->original_info = array(
            'width' => $width,
            'height' => $height,
            'orientation' => $this->get_orientation(),
            'exif' => null,
            'format' => 'png',
            'mime' => 'image/png'
        );

        if ($color) {
            $this->fill($color);
        }

        return $this;

    }
```

**Comment by claviska** [comment]
Same exact version.

If you're seeing null, then your problem is likely before the image gets passed into this library. This is the exact code I used on the portrait image you provided (assuming the image is already in the directory):

```php
<?php
namespace abeautifulsite;
use Exception;

require '../src/abeautifulsite/SimpleImage.php';

echo '<pre>';
$img = new SimpleImage('20160101_133550.jpg');
var_dump($img->get_original_info());
```

The result, truncated for clarity after EXIF orientation part:

```
array(6) {
  ["width"]=>
  int(5312)
  ["height"]=>
  int(2988)
  ["orientation"]=>
  string(9) "landscape"
  ["exif"]=>
  array(56) {
    ["FileName"]=>
    string(19) "20160101_133550.jpg"
    ["FileDateTime"]=>
    int(1451673714)
    ["FileSize"]=>
    int(4754663)
    ["FileType"]=>
    int(2)
    ["MimeType"]=>
    string(10) "image/jpeg"
    ["SectionsFound"]=>
    string(35) "ANY_TAG, IFD0, THUMBNAIL, EXIF, GPS"
    ["COMPUTED"]=>
    array(12) {
      ["html"]=>
      string(26) "width="5312" height="2988""
      ["Height"]=>
      int(2988)
      ["Width"]=>
      int(5312)
      ["IsColor"]=>
      int(1)
      ["ByteOrderMotorola"]=>
      int(0)
      ["ApertureFNumber"]=>
      string(5) "f/1.9"
      ["UserComment"]=>
      NULL
      ["UserCommentEncoding"]=>
      string(9) "UNDEFINED"
      ["Thumbnail.FileType"]=>
      int(2)
      ["Thumbnail.MimeType"]=>
      string(10) "image/jpeg"
      ["Thumbnail.Height"]=>
      int(288)
      ["Thumbnail.Width"]=>
      int(512)
    }
    ["ImageWidth"]=>
    int(5312)
    ["ImageLength"]=>
    int(2988)
    ["Make"]=>
    string(7) "samsung"
    ["Model"]=>
    string(8) "SM-G925P"
    ["Orientation"]=>
    int(6)

    ...
    
}
```

If the EXIF data was getting passed in, the `auto_orient()` method would pick up the `6` and flip it accordingly. Since the EXIF data is missing, it assumes there's nothing to do.

Like I said, if you're truly seeing null from the snippet above, the issue is before the image ever gets passed in to this library.

**Comment by brittonk** [comment]
Solved. I feel silly... but for some reason EXIF wasn't included in the php5.x whatever build. I recompiled php with EXIF and it works now.

For anyone else that encounters this in the future, make sure you see EXIF as a complete section in your phpinfo(); -- it appeared in other places so I assumed all was well.

Thanks for your help claviska
