### ISSUE TITLE
Undefined index: Orientation

### ISSUE THREAD

**Issue by xxalfa** [claviska/SimpleImage#117]
Notice:  Undefined index: Orientation in /Applications/XAMPP/xamppfiles/htdocs/SimpleImage.class.php on line 91

This Line: switch ($this->original_info['exif']['Orientation']) {

**Comment by claviska** [comment]
We currently only test with warnings and errors. Disabling PHP notices will fix that.

```php
error_reporting(E_ALL & ~E_NOTICE);
```
