### ISSUE TITLE
Add image to another image ,or add backgroud with special width and height

### ISSUE THREAD

**Issue by mrhmansour** [claviska/SimpleImage#118]
from 
![1dac4g](https://cloud.githubusercontent.com/assets/4543301/12378107/c8797ce2-bd3c-11e5-95a4-86650bca74cd.jpg)

to 
![new](https://cloud.githubusercontent.com/assets/4543301/12378108/c8b3ca82-bd3c-11e5-8960-894b2be94d3d.jpg)

**Comment by claviska** [comment]
Is this a feature request? You can do this with the `overlay()` (add image to another image) and `create()` / `resize()` methods.

**Comment by mrhmansour** [comment]
code :

    $img = new abeautifulsite\SimpleImage("1.jpg");
    $img->overlay("2.jpg", 'bottom right', .5, -10, -10)->save("3.jpg");

![1](https://cloud.githubusercontent.com/assets/4543301/12531936/ab3793ee-c20f-11e5-8a8a-9305f68fcb5b.jpg)
![2](https://cloud.githubusercontent.com/assets/4543301/12531937/ab3cabcc-c20f-11e5-8748-3b712b0460f8.jpg)

result :
![3](https://cloud.githubusercontent.com/assets/4543301/12531938/ab40fe52-c20f-11e5-870f-212a0624ab99.jpg)

where it's 2.jpg ?

**Comment by claviska** [comment]
I think this is what you're trying to do:

```php
// First image
$img1 = new SimpleImage('1.jpg');

// Second image (resized to 200 width)
$img2 = new SimpleImage('2.png');
$img2->fit_to_width(200);

// Place the second image on top of the first
$img1->overlay($img2, 'bottom right', .5, -10, -10)->save('3.jpg');
```

Which will produce this image:

![3](https://cloud.githubusercontent.com/assets/55639/12559948/fac23cd2-c365-11e5-9160-383aacecb086.jpg)
