### ISSUE TITLE
Image border/stroke

### ISSUE THREAD

**Issue by oknoorap** [claviska/SimpleImage#119]
Any ideas how to create image's border using SimpleImage?

**Comment by mdehaas** [comment]
Create a new image Completely white 20 pixels wider and taller than the original and watermark the original image at offset 10,10. Do not add transparency. Would that work?

**Comment by claviska** [comment]
That would technically work but would make the image larger than desired. For a proper stroke/border effect we'll have to add a method.

I'll leave this open as a feature request until I (or someone else) can get to it.

Parameters for this method should include:

$width = 1
$color = '#000000'

And depending on complexity:

$type = 'solid' (dashed, dotted, double, etc.)

Would love contributions if someone has the time :)
