### ISSUE TITLE
Request: Support for animated GIFs

### ISSUE THREAD

**Issue by HoverAlex** [claviska/SimpleImage#124]
Will there be support for animated gifs soon?

**Comment by claviska** [comment]
Unlikely. SimpleImage is primarily a wrapper for GD, and GD doesn't support animated GIFs.

**Comment by bengalamx** [comment]
@claviska is there a way to maintain the animation? For website ads, clients sometimes needs rotation images, so they use gifs. And well, gifs are for that.

**Comment by claviska** [comment]
Not with GD. The library simply doesn't support AGIF.

**Comment by claviska** [comment]
There may be a workaround in PHP but that would involve breaking the image down frame by frame, modifying each image, then reassembling it. I'm not aware of an elegant solution in PHP, and one would likely be memory intensive.

[This might help](https://stackoverflow.com/questions/718491/resize-animated-gif-file-without-destroying-animation) if you have ImageMagick available.
