### ISSUE TITLE
Composer is getting old version

### ISSUE THREAD

**Issue by h2u** [claviska/SimpleImage#133]
Composer does not update package with new functions like "focals" for "thumbnail".

**Comment by rjgamer** [comment]
Composer isn't working anymore for SimpleImage...

**Comment by claviska** [comment]
Explain. I just ran a Composer install this week for a project and SimpleImage was installed just fine.

**Comment by claviska** [comment]
Anyone else having this issue? If so, please open a new ticket with details. Thanks :)
