### ISSUE TITLE
Transparent PNG to JPG - black background.

### ISSUE THREAD

**Issue by michalq** [claviska/SimpleImage#134]
For transparent PNGs converted to JPGs, transparency is chenged to black.

http://stackoverflow.com/questions/9632573/php-png-to-jpg-conversion-issue-image-distorted?answertab=active#tab-top

**Comment by claviska** [comment]
This can be done by creating a new image with whatever background color you want and overlaying the transparent PNG on top of it.

This is off the top of my head so it might need adjustments:

```php
$png = new SimpleImage('image.png');

$jpeg = new SimpleImage();
$jpeg->create($png->width, $png->height, '#ffffff')->overlay($png)->save('new-image.jpg');
```

**Comment by nikmauro** [comment]
The width and height not working,
Member has protected access
