### ISSUE TITLE
resizing images

### ISSUE THREAD

**Issue by dnsBlah** [claviska/SimpleImage#136]
Hi all,

just a small question.
I'd like to create thumbnails of photos to expose them on a overview page.

These thumbs should be 90x90 150x150 300x300
But the original images are not square

I'm using
`$tImg = new abeautifulsite\SimpleImage($tPath);
$img1 = $tImg->best_fit(90,90);`

Which works like desired regarding the scale etc of the source image, but now I want to make sure that the image I'm going to save is actually 90x90 and not.. 90x70 or 70x90, and needs to be transparent.

I save everything to .png

Hopefully someone can help me out here love this class!

**Comment by claviska** [comment]
Try the thumbnail() method with both width and height set.
