### ISSUE TITLE
Resized PNG does not reduce file size as much as resized JPEG

### ISSUE THREAD

**Issue by wshin93** [claviska/SimpleImage#138]
Hello,
I love this class as it is so easy to use, I have used it to crop and resize image uploaded into my website. However I do have a question:

When cropping and resizing a 2MB 4K JPEG image to 1200*656, it can produce a small JPEG file (around 70KB) which is great!
However when cropping and resizing a similar PNG image (1.6MB 4K PNG) the resulting image size was pretty big 600ish KB.

Seems like resizing a PNG image does not reduce the file size as huge as resizing JPEG image does.
Is it because the PNG file type limitation? or is there any other way to get smaller file size?

Thank you.

**Comment by claviska** [comment]
That's entirely dependent on the image. JPEGs are lossy and compress photos well.

PNGs are lossless, so depending on the actual image the size can vary widely. For example, a logo with three colors will compress much better than a complex photograph of the same width and height.

There are additional optimizations you can try, but they rely on binaries. Here's a wrapper for some common libs:

https://github.com/bensquire/php-image-optim

**Comment by wshin93** [comment]
Hello! 
Well I guess there's not much we can do to reduce PNG size then.
Anyway thank you for the explanation and suggestion, really appreciate it!
