### ISSUE TITLE
Simple Image cropped with extraspace fill with transparent png

### ISSUE THREAD

**Issue by BenjaminPiscart** [claviska/SimpleImage#139]
Hi,

I have and image cropped with extra space, so the background is fill with black (png).
Process: Fixed ratio, zoom out, the uploaded image is smaller than the crop selection.

I want to have the same result but this transparent background.

Is it possible to merge a SimpleImage in an other one ?
I mean replacing $desImgPath in ($imgTransparent->overlay($destImgPath, 'center', 1);) with a SimpleImage instance.

```
        $img            = new SimpleImage($imgPath);    
        $img->crop(round($x1), round($y1), round($x2), round($y2));
        $img->save($destImgPath);
        $imgTransparentPath     = sfConfig::get('sf_upload_dir') . '/sample/transparent-230-177.png';
        $imgTransparent         = new SimpleImage($imgTransparentPath);    
        $imgTransparent->overlay($destImgPath, 'center', 1);
        $imgTransparent->save($destImgPath); 
```

exemple: https://drive.google.com/open?id=0B08Stcy7I35rdFY0ZWxkSGpkN1E

**Comment by claviska** [comment]
Yes, the `overlay()` method supports an [image filename or a SimpleImage object](https://github.com/claviska/SimpleImage/blob/master/src/abeautifulsite/SimpleImage.php#L718).
