### ISSUE TITLE
Unable to upload and modify image from form

### ISSUE THREAD

**Issue by Intruders** [claviska/SimpleImage#140]
I have form uploading various images at once where I can upload them all with simple php coding but wanted to have the option to create a thumbnail and save it another folder.
I have try the debugging method but no message pops up to see the error.

here is the code i have:

$count=0;             
    					foreach($_FILES["image"]["name"] as $filename) 
    					{
    						$image_tmp = $_FILES["image"]["tmp_name"][$count];
    				    	$image_name = $_FILES["image"]["name"][$count];
    				    	$image_error = $_FILES["image"]["error"][$count];
    				    	$image_size = $_FILES["image"]["size"][$count];
    				    	$image_type = $_FILES["image"]["type"][$count];
    				    	
    				    	list($width, $height, $type, $attr) = getimagesize($image_tmp);
    				    	
    				    	if($image_error > 0) 
    						{
    							echo "<script>$(document).ready(function() {error('Error: ".$image_error."')});</script>";
    						}
    						elseif($image_size > "3145728")
    						{
    							echo "<script>$(document).ready(function() {error('One of your Images is bigger than 3MB!')});</script>";
    						}				
    						else
    						{
    							if($image_type == "image/gif" || $image_type == "image/png" || $image_type == "image/pjpeg" || $image_type == "image/jpg" || $image_type == "image/jpeg") 
    							{
    								$query_select_id = mysqli_query($ligacao, "SELECT max(id) FROM gallery");
    								$idMax = mysqli_fetch_assoc($query_select_id);
    								$id = $idMax["max(id)"]+1;
    								
    								// Upload original images
    								$image = explode(".", $image_name);
    								$thumbnail = "gallery-".$id.".".end($image);
    								$image = "gallery-".$id.".".end($image);
    								
    								// Upload resized images

                                    
                                    try {
                                    $resize = new SimpleImage($image_name);
                                    $resize->thumbnail(400, 300)->save($album_path."thumbnails/".$thumbnail);
} catch(Exception $e) {
    echo 'Error: ' . $e->getMessage();
}
    								
    								move_uploaded_file($image_tmp, $album_path."images/".$image);
    								
    								$query_insert_project = mysqli_query($ligacao, "INSERT INTO gallery(image, active, id_album) VALUES ('$image', '1', '$id_album')");
    								
    							}
    							else
    							{
    								echo "<script>$(document).ready(function() {error('One of your Images is not a valid format!')});</script>";
    							}
    						}
    						
    						$count = $count + 1;          
    					}

**Comment by claviska** [comment]
If you're not reporting an issue with SimpleImage itself, please post your question on StackOverflow or a similar site. You're more apt to get a helpful and faster response there.

This issue tracker is for bugs and feature requests related to the library itself, not implementation issues.

Thanks for understanding.
