### ISSUE TITLE
Text Position

### ISSUE THREAD

**Issue by bado57** [claviska/SimpleImage#142]
Hi many thanks example.
http://phpimageworkshop.com/tutorial/1/adding-watermark.html

This sample in 6 th parth text position cross or flat, but your example, I can not do it cross position, TOP-RİGHT/CROSS.

Another situation, writing on watermark. 
Please help me. God chance.

**Comment by claviska** [comment]
Hi, that's a different class with a different API. To use SimpleImage, please refer to the examples in the readme file. Additional info can be found in the code until we get better documentation :)
