### ISSUE TITLE
Method: Most used color

### ISSUE THREAD

**Issue by lorvent** [claviska/SimpleImage#144]
Hello,
Great library, want to use for some batch operations on cli.

do you have any plans to add to find which color is most used in an image?

Thanks.

**Comment by claviska** [comment]
We talked about this in #27. Two problems that still exist are licensing and overhead.

It's easy enough to use [color-thief-php](https://github.com/ksubileau/color-thief-php) on its own, so doubling the size of SimpleImage just to support one feature and having to worry about licensing conflicts isn't really worth it at this point.

**Comment by lorvent** [comment]
why we need to use that package code?

its a simple code where we have to find color of each pixel then find out which is used most,

there are many examples exists in SO aswell.

infact i never know about that package too.

**Comment by claviska** [comment]
1. The license is incompatible.

2. Finding the dominant color involves more than just counting the most frequently used color values. That's easy to do, but it's not useful in a real world application. There are flaws with that method. For example, antialiasing will cause pixels to be visually similar but not the same color value. A proper solution will normalize visually similar colors, which is especially important for photographs and JPEG images.

The library I linked to is a fork of [color-thief](http://lokeshdhakar.com/projects/color-thief/). You can see how well the dominant color and generated palettes are generated [in the demo](http://lokeshdhakar.com/projects/color-thief/). It uses quantize.js to achieve spot on results.

To use color-thief-php, simply require it:

```
composer require ksubileau/color-thief-php
```

And grab the dominant color like this:

```php
$dominantColor = \ColorThief\ColorThief::getColor($image);
```

To get a full color palette, do this instead:

```php
$palette = \ColorThief\ColorThief::getPalette($image, 8);
```
