### ISSUE TITLE
Bug: overlay png image generates only black rectangle

### ISSUE THREAD

**Issue by demmmmios** [claviska/SimpleImage#149]
Hi I found problem when creating overlay image on fixed sized area. Example code:
(origImage i.e. http://www.phpied.com/files/filter/img_filter_grayscale.png)

```
$origImage= new \abeautifulsite\SimpleImage($path);
$origImage->best_fit(500, 500);

$finalImage = new \abeautifulsite\SimpleImage();
$finalImage ->create(500, 500, '#FFFFFF');
$finalImage ->overlay($origImage, 'center', 1);
```

Result is black rectangle into white 500x500 area. It appears only when origImage is smaller than requested image size. 

Temporary fixed by comenting for loop on line 1303 - // Loop through image pixels and modify alpha for each

**Comment by claviska** [comment]
What does `$origImage->output()` show after `best_fit`? Can you post the source image?

**Comment by demmmmios** [comment]
[example.zip](https://github.com/claviska/SimpleImage/files/541198/example.zip) try this full example app

**Comment by claviska** [comment]
Bug confirmed, thanks for the report.

**Comment by claviska** [comment]
Looks like this bug was also resovled in cba4188. Thanks for submitting this.
