### ISSUE TITLE
what about upload?

### ISSUE THREAD

**Issue by siberfx** [claviska/SimpleImage#150]
are you able to integrate to this great image class, -> upload file and then start process ?

**Comment by claviska** [comment]
Sorry, file uploading is way outside the scope of this project. Uploads are best handled through your framework of choice or even with vanilla PHP. Some tutorials:

Slim: https://akrabat.com/psr-7-file-uploads-in-slim-3/
Laravel: https://laravel.com/docs/5.3/requests#retrieving-uploaded-files
No framework: http://www.tizag.com/phpT/fileupload.php
