### ISSUE TITLE
Use overlay with base64 images

### ISSUE THREAD

**Issue by miranos** [claviska/SimpleImage#151]
I just tried to modify the overlay function in order to use base64 image, but everytime i don't get the good result.

`$img->load_base64($image2)->overlay($image, 'top left', .8)->save('butterfly-overlay.jpg');`

Modified this line on overlay function:
```
        // Load overlay image
        if( !($overlay instanceof SimpleImage) ) {
            $overlay = $this->load_base64($overlay);
        }
```

Any fix please ?

**Comment by claviska** [comment]
We don't support modified versions of the library (and you really shouldn't modify any library, as it makes it extremely difficult to update them).

If you need a specific feature you're welcome to request it or, even better, submit a PR.

**Comment by miranos** [comment]
Ok sir, i will follow your advice since it worked fine with the original code !!!

`$img->load("background.png")->overlay($image, 'top left', .8)->save('butterfly-overlay.jpg');`

`$image` is in base64 format !

Can you explaign me how it worked please ?

**Comment by claviska** [comment]
Sorry, I'm not sure what you're asking. In the sample you just provided, the resulting image will be a JPEG file called `butterfly-overlay.jpg`.

What are you trying to base64 encode/decode?

**Comment by claviska** [comment]
If this is still an issue, please provide more info for consideration.
