### ISSUE TITLE
Issue With Some Images

### ISSUE THREAD

**Issue by brittonk** [claviska/SimpleImage#155]
I'm having issues with some images...

when using the simplest of tests it returns the error:
Error: Unable to save image:

Attached is an example photo that does not process.

[20160205_195534.zip](https://github.com/claviska/SimpleImage/files/688515/20160205_195534.zip)

**Comment by claviska** [comment]
Do you have a code sample?

**Comment by brittonk** [comment]
it breaks in my normal/used code on the site so I did a test with your basic implementation code and it breaks there as well and generates that error message.

`include($_SERVER['DOCUMENT_ROOT'].'/js/SimpleImage.php');

try {
    $img = new abeautifulsite\SimpleImage($_SERVER['DOCUMENT_ROOT'].'/image.jpg');
    $img->auto_orient()->save($_SERVER['DOCUMENT_ROOT'].'/result.jpg');
	
} catch(Exception $e) {
    echo 'Error: ' . $e->getMessage();
}`

**Comment by claviska** [comment]
This is what I saw using your test image:

```
Warning: imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG in SimpleImage/src/abeautifulsite/SimpleImage.php on line 1233

Warning: imagecreatefromjpeg(): 'test.jpg' is not a valid JPEG file in SimpleImage/src/abeautifulsite/SimpleImage.php on line 1233
```

Which led me to discover [this setting](http://php.net/manual/en/image.configuration.php). After a9fc06b, the image is saved as expected. Thanks for reporting this.

**Comment by brittonk** [comment]
thanks so much! 💃
