### ISSUE TITLE
Load lot of images

### ISSUE THREAD

**Issue by jafar-rezaei** [claviska/SimpleImage#161]
Hi ,

I am using simple image on my project : http://www.citygram.ir/

The images is located on `http://citygramcdn.ir`

example : 
```
http://citygramcdn.ir/bphoto/Yml6UGhvdG9zLzIwMTcvNzFfemEwZzUuanBnOislRDglQjMlRDklOEElRDglQUElRDklOEErJURBJUFGJUQ4JUIxJUQ4JUE3JUQ5JTg1Kzo6MTM6/770-300/biz_47.ctg
```

As you  see I use base64 encode to pass image data and sizes as url parameter to `CDN` , every thing is okay , but some time some of images not loaded in first site load , and it is not showing any error JUST not loaded image !

you can reload `citygram.ir` and see not loaded images . 

where is the problem ?
is it a hosting problem ?

thanks

**Comment by claviska** [comment]
No idea. Are you sure that's not a problem with your CDN?

**Comment by jafar-rezaei** [comment]
I do not thinks so , 
when I try load NOT loaded image directly , it will be load ... 

I use `toScreen` and `toFile` together to save a cache of image and do not make thumbnail again like :  
`$image->toFile(getcwd() . "/cache/".$this->pathToCache."/".basename($this->file) , "image/jpeg")->toScreen();`

and in every trying to load image check available cache and then make tumbnail :  
`
    private function handleCaching() {


        $this->pathToCache = $this->action."/".$this->width."-".$this->height;



        // create cache directory
        if (!file_exists("cache/".$this->pathToCache)) {
            mkdir("cache/".$this->pathToCache , 0755 , true);
        }


        // Load cached image and dont create thumbnail
        $basenameFile = basename($this->file);

        if(file_exists("cache/".$this->pathToCache."/".$basenameFile)){

            $this->doThumbing = false;
            $ext = pathinfo($basenameFile, PATHINFO_EXTENSION);
            switch(strtolower($ext)) {
                case "gif":
                    header("Content-type: image/gif");
                    break;
                case "png":
                    header("Content-type: image/png");
                    break;
                case "jpg":
                    header("Content-type: image/jpeg");
                    break;
                case "jpeg":
                    header("Content-type: image/jpeg");
                    break;
            }
            
            // Getting headers sent by the client.
            $headers = apache_request_headers();

            // Checking if the client is validating his cache and if it is current.
            if (isset($headers['If-Modified-Since']) && (strtotime($headers['If-Modified-Since']) == filemtime($this->file))) {
                // Client's cache IS current, so we just respond '304 Not Modified'.
                header('Last-Modified: '.gmdate('D, d M Y H:i:s', filemtime("cache/".$this->pathToCache."/".$basenameFile)).' GMT', true, 304);
            } else {
                // Image not cached or cache outdated, we respond '200 OK' and output the image.
                header('Pragma: public');
                header('Cache-Control: max-age=2592000');
                header('Expires: '. gmdate('D, d M Y H:i:s \G\M\T', time() + 2592000));
                header('Last-Modified: '.gmdate('D, d M Y H:i:s', filemtime("cache/".$this->pathToCache."/".$basenameFile)).' GMT', true, 200);
                header('Content-Length: '.filesize("cache/".$this->pathToCache."/".$basenameFile));
                print file_get_contents(getcwd()."/cache/".$this->pathToCache."/".$basenameFile);
                exit();
            }

        }else{

            $this->doThumbing = TRUE;
        }

    }
`

**Comment by claviska** [comment]
I'm not sure either, but I don't think it's a problem with the library. Might be a good question for StackOverflow since it will get more eyes on it.

**Comment by jafar-rezaei** [comment]
ok , I have 2 question , 
1. is it important the order of `toScreen` and `toFile` ? 
2. in `toFile` method and 'toScreen` method we have twice `$image = $this->generate($mimeType, $quality);` if we use both of them the `generate` method will called twice and spent more time and more memory ?

**Comment by claviska** [comment]
1. The order shouldn't matter as long as you realize that `toScreen` will produce a `Content-Type` header.

2. This will call `generate()` twice internally which will take twice as long to process on your server. I'd recommend using `toFile` and then streaming it with [`readfile`](http://php.net/manual/en/function.readfile.php) (with an appropriate `Content-Type` header) since you're already saving it to disk.

The saver methods are really better used individually since we're not storing the generated image internally (for memory reasons).

**Comment by jafar-rezaei** [comment]
whats your idea about create a new method like `toScreenAndFile` . like : 
```php 
  public function toScreenAndFile($file, $mimeType = null, $quality = 100) {
    $image = $this->generate($mimeType, $quality);

    // Save the image to file
    if(!file_put_contents($file, $image['data'])) {
      throw new \Exception("Failed to write image to file: $file", self::ERR_WRITE);
    }

    // Output the image to stdout
    header('Content-Type: ' . $image['mimeType']);
    echo $image['data'];

    return $this;
  }
```

where you think use `readFile` ?

**Comment by claviska** [comment]
I think this is an edge case and it would create bloat since you can output the image directly with two lines once the file is written:

```php
  $image = new \claviska\SimpleImage('source.jpg');
  $image->doSomething();
  $image->toFile('dest.jpg');

  header('Content-Type: ' . $image->getMimeType);
  readfile('dest.jpg');
```

**Comment by claviska** [comment]
If you reduce your code and do find an issue with the library, feel free to comment for further review. 🙂
