### ISSUE TITLE
Get imagettftext array back using text() method

### ISSUE THREAD

**Issue by dixiedream** [claviska/SimpleImage#164]
It would be nice to have the imagettftext array return value in order to place a second text next to the first. Maybe saving it as a lastText position array property.

Overall great work!

**Comment by claviska** [comment]
Good idea. With 9b40cc8 you can now pass a third argument which will be populated by reference.

Example:

```php
$image = new \claviska\SimpleImage('image.png');
$image
  ->text('Some Text', [
    'fontFile' => 'font.ttf',
    'size' => 50,
    'color' => 'white',
    'anchor' => 'center'
  ], $box)
  // Draws a rectangle around the text
  ->rectangle($box['x1'], $box['y1'], $box['x2'], $box['y2'], 'red');
```

**Comment by claviska** [comment]
Also see #165 which addresses a long-standing text positioning bug.
