### ISSUE TITLE
Support for alternative to GD

### ISSUE THREAD

**Issue by Marchrius** [claviska/SimpleImage#169]
Is there a chance to support an alternative image processing library other than GD? It's well known that GD uses a lot of memory and in some case is very "slow". So, have you considered to use an alternative image processing library?

**Comment by claviska** [comment]
GD is a beast, but it's the only extension PHP "embraces" for images, and a lot of folks have trouble installing ImageMagick for some reason.

Thus, I made this library to normalize unexpected GD behaviors, improve alpha transparency support, and offer an easier API for working with images. Many of the issues it addresses don't occur in other extensions (and I believe the ImageMagick one even has an OOP API).

That said, I'm open to an experimental branch to add support for ImageMagick/GraphicsMagick, but if the code gets too crazy it might be better to work it in as a fork instead.

I just spent a lot of time reworking SimpleImage 3 and won't have time to work on this myself. It would be more likely that I adapt it for Node as that would better align with a project I'm working on.

I'll leave this open for consideration!

**Comment by Marchrius** [comment]
Thank you for response and clarifications. At the moment I can't develop a branch of SI using ImageMagick or other external library but I'll try to do something in the spare time.

Your considerations are strongly supported by the _native_ support of GD in PHP than other external library and for the primary aim of the project. It's hard to tell whether it makes sense to create something like this with an _unsupported natively_ library.

**Comment by claviska** [comment]
Right. If you plan on releasing an installable PHP app, adding ImageMagick/GraphicsMagick as a requirement will cause a lot of problems and limit your install base.

It seems like the only reason GD still exists is for PHP devs who are stuck using it. 🤷🏻‍♂️

**Comment by claviska** [comment]
This is sort of outside the scope of SimpleImage. There haven't been any 👍  or similar requests, and there are other libraries for ImageMagick so it's probably best to use those instead.
