### ISSUE TITLE
Tiled Overlay

### ISSUE THREAD

**Issue by rsiemoneit** [claviska/SimpleImage#170]
Hi Cory,

what about a tiled overlay? Maybe the function could look something like that:

```php
function overlayTiled($overlay, $opacity = 1, $xOffset = 0, $yOffset = 0, $xMargin = 10, $yMargin = 10) {
    // do the magic stuff here
}
```

There could be also parameters for the count of overlay in x and y direction.

**Comment by claviska** [comment]
Is this what you have in mind?

![test](https://cloud.githubusercontent.com/assets/55639/22223745/0523d576-e18a-11e6-888b-eb9591b5b9e1.jpg)

This is pretty easy to achieve using transparent white/black lines. Here's a quick example:

```php
// Tile effect
$size = 30;
for($x = 0; $x < $image->getWidth(); $x += $size) {
  for($y = 0; $y < $image->getHeight(); $y += $size) {
    $image->line($x, $y, $x + $size - 1, $y, 'white|.25'); // top
    $image->line($x, $y, $x, $y + $size -1, 'white|.25'); // left
    $image->line($x, $y + $size - 1, $x + $size - 1, $y + $size - 1, 'black|.25'); // bottom
    $image->line($x + $size - 1, $y, $x + $size - 1, $y + $size - 1, 'black|.25'); // right
  }
}
```

You could do this with per-pixel precision, but it would be expensive to iterate each pixel. If that's not an issue, experiment with `getColorAt()` to get the current color, `lightenColor()` and `darkenColor()` to manipulate it, and `dot()` to replace it.

**Comment by rsiemoneit** [comment]
No, but it also looks nice. 

![test](https://cloud.githubusercontent.com/assets/25154118/22226861/8c577988-e1c8-11e6-8475-b678c234a70e.jpg)

That's what i'm trying to achive. And nearly 90% are done. And all with your class.

**Comment by claviska** [comment]
Ah tiled image overlay. This could be done by applying overlay a number of times, but that could be expensive too. I believe you can set a full pattern in GD so the best approach might be to create a new temp image, fill with the watermark "pattern," and merge it onto the original.

In that case I think your arguments look pretty good. I'll entertain a PR if you want to submit one, otherwise I'll work on it in my spare time.

**Comment by claviska** [comment]
Closing since this can be done by looping the width/height and applying an overlay. Won't be expensive as I initially thought since you'd only be loading the overlay once. Should be pretty quick, actually.
