### ISSUE TITLE
WebP file type conversion

### ISSUE THREAD

**Issue by nikmauro** [claviska/SimpleImage#173]
About Webp
https://jmperezperez.com/webp-placeholder-images/

php
http://php.net/manual/en/function.imagewebp.php

**Comment by claviska** [comment]
WEBP is already supported, but not all environments support it. It yours doesn't and you try to read/write that format, you'll receive an error with the `ERR_WEBP_NOT_ENABLED` constant as the error code.

**Comment by Mxater** [comment]
This is not soported.

In line 131
```
        // Get image info
        $info = getimagesize($file);
        if($info === false) {
            throw new \Exception("Invalid image file: $file", self::ERR_INVALID_IMAGE);
        }
        $this->mimeType = $info['mime'];
```
This throw false, because **getimagesize** dont support webp [https://www.php.net/manual/es/function.getimagesize.php](url)
With **WEBP** images, show false Exception.

**Comment by claviska** [comment]
It was [added in 7.1.0](https://www.php.net/manual/en/function.getimagesize.php#refsect1-function.getimagesize-changelog) so you'll need to be using at least that version if you're processing webp.
