### ISSUE TITLE
ToScreen() failed

### ISSUE THREAD

**Issue by krypta83** [claviska/SimpleImage#178]
Generating a image within a single file with method "toScreen();". But it shows only a empty white image. If a use the method "toFile" it works like a charm. I migrated to php 7.1 and cant figure it out.

**Comment by jcamp** [comment]
Did you fix this one...? I get the same issue.

**Comment by claviska** [comment]
Turn on error reporting or check the logs to see if there's any info there. Also make sure you're not outputting the image after content has been written to stdout.
