### ISSUE TITLE
Black background instead of transparent

### ISSUE THREAD

**Issue by drakulitka** [claviska/SimpleImage#179]
Black background instead of transparent for images with the extension * .png

- SimpleImage [v3.3.0](https://github.com/claviska/SimpleImage/tree/3.3.0)
- PHP [v7.1.2-2](https://www.archlinux.org/packages/?name=php)
- php-gd [v7.1.2-2](https://www.archlinux.org/packages/?name=php-gd)
- ArchLinux 4.10.2-1

**Comment by claviska** [comment]
Need example images and a code sample to reproduce. Is the PNG 8-bit or 24-bit? What method(s) seem to be causing it?

**Comment by drakulitka** [comment]
Indeed, the problem was in the image, thanks
