### ISSUE TITLE
bestFit mode was broken

### ISSUE THREAD

**Issue by Poldan** [claviska/SimpleImage#180]
In old versions was:
`// If it already fits, there's nothing to do
    if ($this->width <= $max_width && $this->height <= $max_height && !$force) {
        return $this;
    }`
And if maxWidth = 1000 and maxHeight = 1000, width = 500, height = 500 - script do nothing (it's good)

In new version there is no this string.
And if i have 500x500 img, it will be resized on 1000x1000. Not good. Maybe add $mode = 0 | 1, which case force w and h, or not.

p.s. Sorry for my english.

**Comment by claviska** [comment]
Thank you. That was a bug. An image should never be processed using `bestFit()` assuming it already fits inside the desired width/height. Fixed in 2909eec.
