### ISSUE TITLE
Extend the method overlay()

### ISSUE THREAD

**Issue by bloxcms** [claviska/SimpleImage#181]
I propose to add two parameters to the method overlay().
These are $width and $height of the overlaying image.
So the beginning of method's declaration will be as follows (see #NEWCODE)

```
  public function overlay($overlay, $anchor = 'center', $opacity = 1, $xOffset = 0, $yOffset = 0, $width=null, $height=null) {
    if(!($overlay instanceof SimpleImage)) {
      $overlay = new SimpleImage($overlay);
        #NEWCODE\\\\\\\\\\\\\\\\\\\\\\\\\\\\
        if ($width && $height)
            $overlay->resize($width, $height);
        #NEWCODE////////////////////////////
    }
```

**Comment by claviska** [comment]
Why not use the existing API?

```php
$overlay = new SimpleImage('overlay.png');
$overlay->resize(300, 200)

$image = new SimpleImage('image.png');
$image->overlay($overlay);
```

Overlay works with a SimpleImage object too, so there's no overhead in creating a separate instance for this purpose — it will happen either way. This also gives you more flexibility to rotate/crop/etc. before overlaying, and keeps the overlay method lean.

Hope that helps!

**Comment by bloxcms** [comment]
You are right
