### ISSUE TITLE
bestFit() stretches small images

### ISSUE THREAD

**Issue by Thanty** [claviska/SimpleImage#182]
Hi! SimpleImage 3.x stretches images if their width / height have smaller values.
SimpleImage 2.x didn't do that.

It would be nice to have a third param that will disable/enable stretching.

`bestFit(1000, 1000, true)`

This method was really great in 2.x, I used it to limit the size of all uploaded images, but now it cannot be used this way:

`bestFit(2000, 2000)`

Thanks in advance!

**Comment by claviska** [comment]
It shouldn't do that. Can you post an example image and a small test case?

The first line in the bestFit() method prevents smaller images from getting processed: https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L506

But it doesn't cover edge cases where only one of the dimensions is smaller. Either way, the image _should_ always be resized proportionally, never squished. If that's happening, it's a bug that needs to be fixed. 🙂

**Comment by Thantifaxath** [comment]
Cory, I got it now.
Problem is the latest stable version (3.3.0) differs from version in master branch.
https://github.com/claviska/SimpleImage/blob/3.3.0/src/claviska/SimpleImage.php#L505

**Comment by claviska** [comment]
Fixed in [3.3.1](https://github.com/claviska/SimpleImage/releases/tag/3.3.1).

**Comment by khairil01** [comment]
hi, can i know why i use bestFit(1110 , 500), show error.
![Capture](https://user-images.githubusercontent.com/52581798/61524546-3b8de400-aa49-11e9-8c90-16299a290612.JPG)

**Comment by claviska** [comment]
If you want help, please open a new issue and post some code (a minimal example to reproduce your issue). Thanks!

**Comment by khairil01** [comment]
hi, thanks for responded.. i've opened a new issue. hope u can help me get
through this 😊
