### ISSUE TITLE
imagecreatefrompng(): 'myfile.png' is not a valid PNG file

### ISSUE THREAD

**Issue by masimao** [claviska/SimpleImage#185]
Hi,

I am getting the below error with some files, but they are apparently fine.

```php
imagecreatefrompng(): 'myfile.png' is not a valid PNG file
```

SimpleImage gets the file mime type at line 124 using:

```php
$info = getimagesize($file);
if($info === false) {
    throw new \Exception("Invalid image file: $file", self::ERR_INVALID_IMAGE);
}
$this->mimeType = $info['mime'];
```
I am trying to discover what is causing this and found these answers:

[imagecreatefrompng error - how to detect and handle?](https://stackoverflow.com/questions/2295897/)
[Secure Image Upload, or Bypassing PHP mime-type Check](https://security.stackexchange.com/questions/115317/)

Would be the case to change the use of `getimagesize()` to `mime_content_type()`?

**Comment by claviska** [comment]
Is the file actually a PNG, or is it another format with the PNG extension? Feel free to post it as an example.

**Comment by masimao** [comment]
@claviska, Just as feedback, you are right, the file mime type and extension mismatch, so i installed the fileinfo PHP extension and now i am defining the image extension from the file's mime type with [mime_content_type()](http://php.net/manual/en/function.mime-content-type.php) and the errors stopped to happen, even if a user sends a file with an extension that didn't match with your mime type. I think my upload is more secure now, because i can allow only accepted mime types.

Thanks for your help!
