### ISSUE TITLE
re: Just a thought (resize->thumbnail)

### ISSUE THREAD

**Issue by UltraFlux** [claviska/SimpleImage#186]
**Example One:**
http://imgur.com/a/by9uu
Original: 2048x1366
->thumbnail(440, 330, 'center')
= completely fucked showing only a tiny portion of the image near center (no resize)
I actually thought thumbnail would have resize built into the function scaling down the original image to a near representation of the thumbnail size specifications. Then completing a crop of outer edges to match thumb specs exactly. The end result being essentially the original image with tiny portion of the edges cropped creating a uniform thumbnail. The above is useless...

**Example Two:** 
Trying to resize before thumbnail has no affect
$image
            ->fromFile($filenameOut)
            ->resize(width, height) << using this to reduce dimensions of overly large files before creating thumb but does nothing
            ->thumbnail(850, 637, 'center')                
            ->overlay($_SERVER['DOCUMENT_ROOT'].'/images/watermark.png', 'bottom right')
            ->toFile($newFile, 'image/jpeg', 94);

End result the only way I see this working now is by running it twice. (which should not be required).

Run 1: Resize to near Thumbnail Size
Run 2: Create thumbnail

My suggestion is to either have "thumbnail" resize the org. image automatically then create the thumbnail.

If not that then at least allow resize to be called before thumbnail.

Thoughts?
Options?

**Comment by claviska** [comment]
I just ran the following code using your test image:

```php
$image
  ->fromFile('CU0eTPj.jpg')
  ->thumbnail(440, 330, 'center')
  ->toScreen();
```

Result:

![test](https://cloud.githubusercontent.com/assets/55639/26756624/e64d12dc-4874-11e7-98e1-7a06a0e73e8e.jpg)

I don't have your original `watermark.png` file, but here's what it looks like with an overlay using another PNG:

```php
$image
  ->fromFile('CU0eTPj.jpg')
  ->thumbnail(440, 330, 'center')
  ->overlay('flag.png', 'bottom right')
  ->toScreen();
```

Result:

![test](https://cloud.githubusercontent.com/assets/55639/26756630/0105d230-4875-11e7-8145-865e74126a7a.jpg)

You wrote: 

> completely fucked showing only a tiny portion of the image near center (no resize)
I actually thought thumbnail would have resize built into the function scaling down the original image to a near representation of the thumbnail size specifications. Then completing a crop of outer edges to match thumb specs exactly. The end result being essentially the original image with tiny portion of the edges cropped creating a uniform thumbnail. The above is useless...

Not sure what's so fucked about it. Things seems to be working as intended. You can see that the library does perform a [resize](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L991-L996) and a [crop](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L1055-L1056) in the source.

Maybe your original code has an issue, but the library appears to be working as intended and there haven't been any other reports of this working incorrectly.

**Comment by claviska** [comment]
If you have a minimal test case demonstrating this not working, feel free to post it and I'll reopen.

**Comment by UltraFlux** [comment]
Let me send originals!

I believe the code is yours.

Origional - 2048x1366
http://imgur.com/WFVBFrM

After Thumbnail - 440x330
http://imgur.com/6q59cQF

*CODE*
$image
            ->fromFile($filenameOut)
            ->thumbnail(440, 330, 'center')
            ->toFile($newFile, 'image/jpeg', 94);

Not overly complex code. It simply takes original and runs it through
thumbnail and saves as jpeg.

All that appears to be happening on my end is thumbnail taking 440x330 from
the center of the image, then cropping off the rest.

I will try run the above again as I have made further changes to try and
figure out a solution.

Sincerely,
Grant
