### ISSUE TITLE
Images with no exif data

### ISSUE THREAD

**Issue by kriskd** [claviska/SimpleImage#189]
This is similar to #105. 

In the `autoOrient` method, if an image has no exif data `$exif['Orientation']` will not be set and therefore a notice is thrown.

**Comment by claviska** [comment]
I don't make a specific effort to worry about notices, but I'll accept a PR if it bugs you. Looks like the check got omitted when I wrote version 3.

**Comment by claviska** [comment]
Feel free to open a PR to alleviate this notice.
