### ISSUE TITLE
Version number?

### ISSUE THREAD

**Issue by donum** [claviska/SimpleImage#190]
Hi,

I am currently still on SimpleImage 2.5.3.

**What is the current version number?** It's not mentioned anywhere.

Thanks,
Daniel

**Comment by donum** [comment]
SimpleImage 3.3.1

Found it here: https://packagist.org/packages/claviska/simpleimage

PS: Not everybody is using Composer. :)

**Comment by claviska** [comment]
https://github.com/claviska/SimpleImage/releases
