### ISSUE TITLE
Resize image with SimpleImage and send it directly to Amazon S3

### ISSUE THREAD

**Issue by masimao** [claviska/SimpleImage#191]
Hi,

I asked [this question at StackOverflow](https://stackoverflow.com/questions/44729600/how-to-resize-image-using-simpleimage-and-send-it-directly-to-amazon-s3), i will be glad if someone can give any help.

Resuming, i am sending images do AWS S3 using the SimpleImage `toString()` output, but the browser tries to download the image instead of show it.

**Comment by claviska** [comment]
You're probably not setting the content type. Regardless, this is an S3 question not a SimpleImage question. I try to keep the issue tracker just for bugs.
