### ISSUE TITLE
Method for fit into dimension with fill empty

### ISSUE THREAD

**Issue by Poldan** [claviska/SimpleImage#193]
Is there method for do this with your class?

Image:
![fit](https://user-images.githubusercontent.com/55639/27869090-d7a9babc-616c-11e7-8bdb-ea8d6da3bcf7.png)

Code:
```php
$img->fromFile('some.png')->bestFit(100,100);
```
And result, for example, will be 100x79? How do I add transparent/any color to fill image to 100x100?

**Comment by Poldan** [comment]
For GD i can:
bestFit to 100x79, create blank image 100x100, copy my image to blank, align center.
Maybe, add third argument to bestFit ?
$fillColor.
By default - null, if $fillColor - 'transparent' or '#aabbcc' - fill image to right dimensions?

**Comment by Poldan** [comment]
SOLVED!
$IMG = new \claviska\SimpleImage();
$EMPTY = new \claviska\SimpleImage();
$IMG
->fromFile('1.png')
->bestFit(100,100);//100x79 px
$EMPTY->fromNew(100,100)->overlay($IMG)->toFile('1_.png');//100x100 with filled

**Comment by claviska** [comment]
Overlay is pretty much the best approach here. Glad you worked it out.

(I've edited your comments to provide proper code formatting for future visitors.)
