### ISSUE TITLE
Fill BG When Proportional Resize Underfills Outside Dimensions?

### ISSUE THREAD

**Issue by uwecmyersjj** [claviska/SimpleImage#195]
I'd like to be able to proportionally resize an image, but export a consistent height/width image with the BG filled with a specific color if the resized image underfills the outside dimensions.

For example, I have a 100 x 200 image, but I'd like to export a 100 x 100 image in the end.
The resize would bring the original down to 50 x 100, but we'd center that image and have 25 pixels of BG color on the top/bottom of the 100 x 100 image that will be exported.

Is this possible with the existing code?

**Comment by claviska** [comment]
1. Create two SimpleImage objects, one with the image to resize and another with the desired dimensions and background color. 

2. Resize the first image accordingly.

3. Use the overlay method to place it onto the second image.
