### ISSUE TITLE
makeTextBlock method(abeautifulsite/SimpleImage) missing

### ISSUE THREAD

**Issue by upadrian** [claviska/SimpleImage#196]
Some time ago, I used this class but under a abeautifulsite namespace to insert text over a image.
In this version of SimpleImage, the metod makeTextBlock is missing.
This method calculates the lines of text wrapping the entire phrase.

It's missing beacuse this functionality is elsewhere? Or is missing for another reason?

`public function makeTextBlock($text, $fontfile, $fontsize, $width) {
		$words = explode(' ', $text);
		$lines = array($words[0]);
		$currentLine = 0;
		for ($i = 1; $i < count($words); $i++) {
			$lineSize = imagettfbbox($fontsize, 0, $fontfile, $lines[$currentLine] . ' ' . $words[$i]);
			if ($lineSize[2] - $lineSize[0] < $width) {
				$lines[$currentLine] .= ' ' . $words[$i];
			} else {
				$currentLine++;
				$lines[$currentLine] = $words[$i];
			}
		}
		return $lines;
	}`

**Comment by claviska** [comment]
Where are you finding that? That last 2.x release doesn't have that method.

If you're looking for text wrapping in 3.x, refer to this issue: https://github.com/claviska/SimpleImage/issues/137

**Comment by upadrian** [comment]
First, in an old project, i have SimpleImage.php 
/**
 * @package     SimpleImage class
 * @version     2.5.5
 * @author      Cory LaViska for A Beautiful Site, LLC (http://www.abeautifulsite.net/)
 * @author      Nazar Mokrynskyi <nazar@mokrynskyi.com> - merging of forks, namespace support, PhpDoc editing, adaptive_resize() method, other fixes
 * @license     This software is licensed under the MIT license: http://opensource.org/licenses/MIT
 * @copyright   A Beautiful Site, LLC
 *
 */

So, today, i need some image functionality and serched on google.
Found this Github repo and is the same class, but better.

I have successfully used this function to create the lines of text(wrapping the text) and get the lines into an array.
Then, I loop into the array and create the text with ->text()

**Comment by claviska** [comment]
2.5.5. source: https://github.com/claviska/SimpleImage/blob/0e69996a1df1b4eda4d0e81c8aeef9c131f99772/src/abeautifulsite/SimpleImage.php

I still don't know where you got that method from (maybe a fork?).

Regardless, text wrapping is [an open issue](#137). If you have an elegant solution, PRs are always welcome.

**Comment by upadrian** [comment]
Thank's!

Yes, maybe a fork. It was 2 or 3 years since I work on that proyect.
