### ISSUE TITLE
Poor image quality of using resize() method

### ISSUE THREAD

**Issue by terrylinooo** [claviska/SimpleImage#197]
Before:

![rpndz_m](https://user-images.githubusercontent.com/11989371/28907308-171409f6-7850-11e7-993a-e9b25cc32390.jpg)

After bestFit(320,240) :
![rpndz_t](https://user-images.githubusercontent.com/11989371/28907134-1cf5d7ce-784f-11e7-8ff7-f52e90ce154d.jpg)

**Comment by claviska** [comment]
Are you setting the quality param? Need to see some code.

Understand that there's not much we can do about the performance of GD functions, so if that really is the issue there's no sense in reporting it unless you have a solution to offer.

**Comment by claviska** [comment]
Closing due to no response. Feel free to comment with more info.
