### ISSUE TITLE
ttf file cannot be opened/found

### ISSUE THREAD

**Issue by ThreeHDM** [claviska/SimpleImage#199]
I downloaded arial.ttf and passed the argument as an array but I get an error 

> Warning: imagettfbbox(): Could not find/open font in /opt/lampp/htdocs/phpImages/SimpleImage-master/src/claviska/SimpleImage.php on line 889
Unable to load font file:

**Comment by claviska** [comment]
Most likely the path to your font file is incorrect. Not an issue with SimpleImage.

**Comment by ThreeHDM** [comment]
For sure I'm making a mistake, SimpleImage is great!

The file is in the same folder as the index.php file. Could you show me an example snippet or add it to the documentation? Thanks

**Comment by claviska** [comment]
It's just a path like any other file operation.

If it's in the same directory, you can generate a full path like this:

```php
$fontFile = __DIR__ . '/font.ttf';
```

Or from the website root like this:

```php
$fontFile = $_SERVER['DOCUMENT_ROOT'] . '/font.ttf';
```

**Comment by ThreeHDM** [comment]
Thanks
