### ISSUE TITLE
undefined  function

### ISSUE THREAD

**Issue by uniquechukwuma** [claviska/SimpleImage#204]
In my Local Host it works well but when i go online i see this. please help. Fatal error: Call to undefined function claviska\imagepalettetotruecolor() .

If there is an easy way to write on image as well with this class please give me example.
Thanks awesome class

**Comment by uniquechukwuma** [comment]
Please if you have any suggestion on how to solve it let me know

**Comment by claviska** [comment]
Your PHP version is probably out of date. That function requires PHP 5.5+:

http://php.net/manual/en/function.imagepalettetotruecolor.php
