### ISSUE TITLE
Thumbnail() generates black bottom border 

### ISSUE THREAD

**Issue by gurkankara** [claviska/SimpleImage#207]
I tried to thumbnails in my project. Thumbnail method generates 1px black border on the thumbnails.  Is there a solution?

try {
	    	$image = new SimpleImage();
	    	$image->fromFile($F.$N)->autoOrient()->thumbnail($thumb_img_w, $thumb_img_h)->toFile($F.$NT);
	    	$image->fromFile($F.$N)->autoOrient()->thumbnail($img_w, $img_h)->toFile($F.$NC);
	    } catch(Exception $err) {
	    	echo $err->getMessage();
	    }
![screenshot_1](https://user-images.githubusercontent.com/8336522/30811948-48224d32-a212-11e7-907a-137844305605.jpg)

**Comment by claviska** [comment]
Need to see the original image and desired width/height.

**Comment by gurkankara** [comment]
There is no exception, every size of images generates border. Thumbnail sizes depend on variables but they are generates border every size of thumbnails. Like this:

![screenshot_2](https://user-images.githubusercontent.com/8336522/30813279-a9568eb2-a215-11e7-9b4b-88db2211419f.jpg)

**Comment by claviska** [comment]
Just created this thumbnail without a border.

```php
$image
  ->fromFile('parrot.jpg')
  ->autoOrient()
  ->thumbnail(250, 200)
  ->toScreen();
```

You can modify `example/index.php` and run it if you like. Here's the result:

![example](https://user-images.githubusercontent.com/55639/30813551-bb3ac858-a1db-11e7-98b8-8f46a897eef1.jpg)

This method has been stable for quite some time, so it's interesting that nobody else has reported this. That means it's likely an issue with your code or possibly an unexpected CSS style. If you look at the raw image (outside of a browser) is the line still there?

**Comment by gurkankara** [comment]
I think this is a GD library problem. In my localhost, border appears but in my hosting there is no border.

Here is the localhost GD info
![screenshot_3](https://user-images.githubusercontent.com/8336522/30814391-aec3acce-a218-11e7-95c9-ba746213ffc9.jpg)
And the hosting GD info
![screenshot_4](https://user-images.githubusercontent.com/8336522/30814405-b9ae6aac-a218-11e7-905f-42bdfbcfd44d.jpg)

**Comment by claviska** [comment]
You might be onto something. This is possibly related: https://github.com/libgd/libgd/issues/329

Perhaps try updating php-gd on your dev box.

**Comment by claviska** [comment]
Closing since this appears to be an issue with an odler version of GD.
