### ISSUE TITLE
Resize & Crop with Background Fill

### ISSUE THREAD

**Issue by maicolbruski** [claviska/SimpleImage#210]
Hi,

Sugestion for next version, create a image with resize to bestfit and crop with fill background color:

ex:
![simple-image](https://user-images.githubusercontent.com/3951164/32140822-7e215006-bc55-11e7-9898-eef2da5ec0b4.jpg)

Tks!

**Comment by claviska** [comment]
I'm not 100% sure what you're asking. You said "crop with fill background color" but the resulting image looks like it's been enlarged vertically.

What I believe you're asking can be done like this. This ensures `$img1` fits within an 800x800 box and then overlays it onto an 800x800 image with a white background:

```php
$img1 = new SimpleImage('shoe.jpg');
$img1->bestFit(800, 800);

$img2 = new SimpleImage();
$img2
  ->fromNew(800, 800, 'white')
  ->overlay($img1)
  ->toScreen();
```
