### ISSUE TITLE
cut a picture into a round picture

### ISSUE THREAD

**Issue by 616252396** [claviska/SimpleImage#215]
Hello
I want to cut a picture into a round picture
And then re - synthesis
I tried many times, and I couldn't find a way.

**Comment by claviska** [comment]
I believe this does what you're looking for, although there's nothing built in to the library for that right now:

https://stackoverflow.com/questions/9880503/crop-image-in-circle-php

There's also a YouTube video that demonstrates how to do it:

https://www.youtube.com/watch?v=iuj_opL5rOc

I'd be open to incorporating some sort of masking function that makes this easier, but don't have time to write it myself.

**Comment by 616252396** [comment]
Thank you very much. Thank you very much. I've solved my problem.

By reading your code,

I realized that my English level and front end level are very low
