### ISSUE TITLE
Save converted image to specific path 

### ISSUE THREAD

**Issue by aqil-tariq-confiz** [claviska/SimpleImage#216]
I am using toFile to save an image. I want to write the image on the specific path as I cant write on the root of the project on my server.

I am using this piece of code
`$image->resize($thumbnail->width, $thumbnail->height)->toFile($imageFileName);`

This Exception comes
**Exception: Failed to write image to file: in claviska\SimpleImage->toFile()**

Can you please help us on urgent basis

**Comment by claviska** [comment]
Sounds like a permissions issue, nothing to do with SimpleImage. Make sure your app has permission to write to the location you're saving to.

**Comment by aqil-tariq-confiz** [comment]
can you tell us how we can upload to a specific folder?

**Comment by claviska** [comment]
Just set the full path like so:

```php
$image->toFile('/path/to/image.jpg');
```

The method uses [`file_put_contents($file, ...)`](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L310-L328) so it can be a relative or an absolute path.
