### ISSUE TITLE
Is toDataUri Working? Have any Dependencies?

### ISSUE THREAD

**Issue by brittonk** [claviska/SimpleImage#219]
Im attempting to output as base64 for the first time but it doesn't work for me. Am I doing something wrong?

```php
$image = new \claviska\SimpleImage();
$image->fromNew(1080, 1920)
  ->text($speed . ' mph', array(
  'fontFile' => '/font2.ttf',
  'size' => 200,
  'color' => 'black',
  'shadow' => array('x'=>'5', 'y'=>'5', 'color'=>'white'),
  'yOffset' => 700
  ))
  ->toDataUri('image/png', 100)
```

**Comment by claviska** [comment]
The [toDataUri() method](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L282) returns a string, so you need to do something with it. For example:

```php
$dataUri = $image->toDataUri('image/png');
echo '<img src=\"$dataUri\">";
```

**Comment by claviska** [comment]
What do you mean by "breaks"? The image doesn't render? You get an error?

What happens if you `var_dump()` the value?

**Comment by brittonk** [comment]
Nevermind, I've wasted your time <3 

I had a typo in the php. It works beautifully. Thanks for an amazing script.
