### ISSUE TITLE
->toScreen() as a PSR-7 response

### ISSUE THREAD

**Issue by AnixPasBesoin** [claviska/SimpleImage#220]
Is there a way to return the an image as a PRS-7 response? If it is not in the roadmap then please make this issue as a feature request.

**Comment by claviska** [comment]
There are a number of output methods you can use in conjunction with your
routing library/framework. For example, if you’re using Slim you can send
it as a file with the appropriate content type.

As the existing output methods should suffice, I believe this is outside of
the scope of the library.

**Comment by AnixPasBesoin** [comment]
@claviska Thanx for the quick answer ^^
