### ISSUE TITLE
How to move a image in all directions (left, right, top, bottom) ?

### ISSUE THREAD

**Issue by raazsandee** [claviska/SimpleImage#223]
Hey, I tried to move an centered image, but its only moving left or right... how to move top and bottom ?
I want to move the centered image to the top with 25% padding(gap) from top.
![simpleimage](https://user-images.githubusercontent.com/5063382/39086830-e5b73c00-45b5-11e8-8beb-b5e8e8518993.jpg)

**Comment by claviska** [comment]
Hi, can you clarify what you’re trying to do with some code?

It sounds like you’re going to want to create a new blank image (with
appropriate padding) and overlay the existing on.

**Comment by raazsandee** [comment]
$image
		->fromFile('img/base.png')	// load image
		->overlay('img/overlayimage.png','center')
		->toFile('output/filename.png'); 

I had a base.png which is a background image and i want to overlay a image on it. I want it to be centered in y-axis and i want to move the overlay image to top in on x-axis ( if its css we something like margin -100px ). Check the attached image you will understand clearly.
![simpleimage](https://user-images.githubusercontent.com/5063382/39092015-1f45b572-4620-11e8-8612-fc8de825120f.jpg)

**Comment by claviska** [comment]
Try using overlay with offsets:

```php
// Variables used for clarity
$anchor = 'center';
$opacity = 1;
$xOffset = 0;
$yOffset = -100;

$image->overlay($overlay, $anchor, $opacity, $xOffset, $yOffset);
```

**Comment by raazsandee** [comment]
I missed using $opacity field so the overlay image output is blank, now i given $opacity=1, Its working now, Thanks for you time man.
