### ISSUE TITLE
Need to add option from where image will cropped  (Center, right, left, bottom, top)

### ISSUE THREAD

**Issue by vicky9461** [claviska/SimpleImage#224]
I have  added two function as i required..
May this update will help other too.
[simpleimage.zip](https://github.com/claviska/SimpleImage/files/1986640/simpleimage.zip)

**Comment by claviska** [comment]
You've uploaded an old version (2.5.5). We're now on 3.3.3. If you'd like to suggest changes, please create a pull request for the current version.

If you need help creating a PR, please see: https://help.github.com/articles/creating-a-pull-request/
