### ISSUE TITLE
Text stroke and Color fill to the surroundings of text.

### ISSUE THREAD

**Issue by raazsandee** [claviska/SimpleImage#228]
Hey Claviska, Is there any feature or is it possible to add stroke to text and can we fill with a color to the surroundings of the text.
Below i attached the image, black background is the main image and white layer is the fill layer for the text with some X padding.

To add stroke i tried this but it doesn't worked. https://github.com/claviska/SimpleImage/commit/c2bc518c5905c7f2514e262ae452cbf5edeaac59

![text-fill](https://user-images.githubusercontent.com/5063382/42461874-40aa62d0-83bf-11e8-8a60-41c95af8b0dd.png)

Thank you.

**Comment by claviska** [comment]
As mentioned in the [differences from 2.x](https://github.com/claviska/SimpleImage#differences-from-simpleimage-2x), text stroke was removed in version 3 because the method tended to produce dirty results. It used a hack that basically drew the same text above/below/around the original text to simulate a stroke.

This isn't something GD does natively to my knowledge, so I'd be open to a proper PR for a proper stroke method that produces clean, reliable results.

**Comment by raazsandee** [comment]
Okay, I hope the feature will come soon. Is there any property to fill the space with some color surrounding to the text as i shown in the above image (In above image the space around the text is filled with whilte color with some padding).

**Comment by claviska** [comment]
1. Check out the rectangle method.

2. This was in 2.x and the namespace was changed and a full rewrite occurred. As such, the old repo and the project history is no longer available.

You can simulate this yourself by drawing the text x pixels above, below, to the left, and to the right, before drawing the final text.

**Comment by claviska** [comment]
Search for “useful things to know” in the read me: https://github.com/claviska/SimpleImage/blob/master/README.md

I think that’s what you’re looking for.

**Comment by raazsandee** [comment]
This is what i am trying to get...
![Uploading text-fill-2.png…]()

**Comment by claviska** [comment]
I'm closing this because I don't believe there's a decent way to do this in GD. There are workarounds that sometimes produce _ok_ results, but they aren't something I'm interested in bringing into the library.
