### ISSUE TITLE
Resize image increase it size too much

### ISSUE THREAD

**Issue by bsmartclick** [claviska/SimpleImage#230]
Hi,

I am using your SimpleImage beautiful class, but when i try the resize method in a specific image which is 160kb and [2394x2394] - i try to resize to [2000x2000] - i get an image with size about 1.8mb and after waiting about a 73 seconds. iam resize to a smaller size why iam get size too large with respect to the original image. image is png extension, when i the jpg extension with size 232kb it convert to 855kb but with less time then the png, about 4 seconds.

is there any way to avoid this large size and time & make it always smaller size if i am resizing to smaller dimensions?

i attached the png version if want to make some test.

Thanks,
![a](https://user-images.githubusercontent.com/43085360/45250892-71503f80-b345-11e8-8855-5078ec5d0720.png)

**Comment by claviska** [comment]
This can happen if the output quality is higher than the initial quality.

It can also happen if the image was optimized with a modern optimizer — unfortunately GD doesn’t really do this very well, so the resized version can end up less optimized than the original.

To my knowledge, there’s not much we can do inside of SimpleImage to fix this, but you might consider post-processing the image with an optimizer _after_ modifying them with SimpleImage.

**Comment by claviska** [comment]
I’m not sure — never had to do that.

PHP is way too slow for proper image optimization. You’ll want to use a binary or a web service such as ImageOptim for that.

SimpleImage is a wrapper that makes using the “built-in” image library easier. We try to work around many of its caveats, but there’s only so much we can do with PHP + GD alone.

For more advanced image operations (particularly memory intensive tasks such as optimization and lage image processing) it’s almost always better to install ImageMagick or a similar alternative.

**Comment by bsmartclick** [comment]
Ok, Thanks for your clarifications.
