### ISSUE TITLE
Try again later, or contact the server administrator.

### ISSUE THREAD

**Issue by jilaan** [claviska/SimpleImage#234]
Hi again,

dear when i set my php limit then i get this error, not all images but some images
http://myprintscreen.com/s/wwqu/dfb0c6fe8d

how can i fix it ?

Thanks

**Comment by claviska** [comment]
My guess is the file isn't getting written properly (possibly a memory limit issue and it's getting truncated). Check your PHP error logs to see if there's anything there.

Not a SimpleImage issue though.
