### ISSUE TITLE
How I Add Custom Box Width height 

### ISSUE THREAD

**Issue by jilaan** [claviska/SimpleImage#235]
Hi Dear,

it is possible to i add there in custom box like this,
 http://myprintscreen.com/s/wxku/88f1af078f
link here https://www.pexels.com/photo/bonfire-1454789/

if someone need a custom size to download image so how can i add?

Thanks

**Comment by claviska** [comment]
Please stop opening issues that aren't related to the source code of this project. The questions you're asking are more appropriate for [StackOverflow](https://stackoverflow.com/).

**Comment by jilaan** [comment]
Hello,

dear i know it's not a issue but i open may be you are help me to add this option that's why i ask you.

but your script is really helpful me.

Thanks

**Comment by adaniello** [comment]
@jilaan ok, but simply this section is "Issues" and your isn't an issue. As @claviska reported the questions you're asking are more appropriate for [StackOverflow](https://stackoverflow.com/). Try it!
