### ISSUE TITLE
Suggestion for autoOrient()

### ISSUE THREAD

**Issue by johnabela** [claviska/SimpleImage#238]
I encountered an issue today with autoOrient() that I have never had come up before. Somebody tried to upload a jpg file and it threw an error that `$exif['Orientation']` was not defined. Odd, but, uh, ok.

Anyway, right after the line `$exif = $this->getExif();`, might I suggest adding the following:

		if ( empty($exif['Orientation']) ) {
		    return $this;
		}

Do not really feel like doing a whole pull/request for this simple change, but still thought I should suggest it to ya @claviska .

**Comment by claviska** [comment]
Probably a notice — I usually disable them so they fall through the cracks. Easy fix :)

**Comment by claviska** [comment]
[This block](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L489-L491) will prevent this issue.
