### ISSUE TITLE
error uploading image when resize image using bestFit()

### ISSUE THREAD

**Issue by khairil01** [claviska/SimpleImage#244]
when i uploading the image, its show errors. 
1. **Warning (2): imagesx() expects parameter 1 to be resource, null given [ROOT/vendor/claviska/simpleimage/src/claviska/SimpleImage.php, line 437]**
2. **Warning (2): imagesy() expects parameter 1 to be resource, null given [ROOT/vendor/claviska/simpleimage/src/claviska/SimpleImage.php, line 405]**

I resize the image using bestFit(1110 , 500)

$image = new \claviska\SimpleImage($image);
        $img = $image->bestFit(1110,500);
        $img->toFile($savePath, 'image/png');

**Comment by claviska** [comment]
Check the initial value of $image. Make sure you’re using fromFile() or a similar method to load the image.

**Comment by claviska** [comment]
Closing due to no response. If this is still an issue, please post more info and we'll try to help.
