### ISSUE TITLE
imageresolution()  (PHP 7 >= 7.2.0)

### ISSUE THREAD

**Issue by ogito** [claviska/SimpleImage#247]
Hi,

I'm getting the following error:
Fatal error: Uncaught Error: Call to undefined function claviska\imageresolution()

It seems the imageresolution() has been available up to php 7.2.0:
https://www.php.net/manual/en/function.imageresolution.php

Can you please help to replace this function?
Thank you!

**Comment by claviska** [comment]
It looks like it was introduced in PHP 7.2:

```
(PHP 7 >= 7.2.0)
```

To get access to this method, you'll need to be using PHP 7.2 or higher. Since this is a GD function, I'm not really interested in providing a polyfill.
