### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by webooindia** [claviska/SimpleImage#249]
First thanks for great script/code.
Is possible to use multiple overlay image.
 - I want to add overlay logo on top left and contact info in bottom right.

is possible above solution if yes please guide me....

**Comment by claviska** [comment]
Yes, use `overlay` multiple times.

```php
 $image
    ->fromFile('image.jpg')
    ->overlay('logo.png', 'top left')
    ->overlay('contact.png', 'bottom right')
    ->toFile('new-image.png', 'image/png');
```
