### ISSUE TITLE
I got weird result

### ISSUE THREAD

**Issue by Cvar1984** [claviska/SimpleImage#253]
I got weird result by doing
```php
<?php
$image1 = $image2 = $image3 = new \claviska\SimpleImage();
```
Or
```php
<?php
// parent
public static function getContainer() {
    $container = new \Pimple\Container();
    $container['image'] = function()
    {
        return new \claviska\SimpleImage();
    };
    return $container;
}
// child
$container = parent::getContainer();
$image1 = $container['image'];
$imgae2 = $container['image'];
$image3 = $container['image'];
```
![quote](https://user-images.githubusercontent.com/32727560/82936527-4c8c7780-9fc1-11ea-8e91-1c2ccfdb29dc.jpg)

**Comment by claviska** [comment]
Not sure exactly what you're trying to do, but try creating a unique instance for each image. Reusing the same image resource is probably causing the weirdness you're seeing.

If you're submitting a bug report, please provide a minimal test case to clearly demonstrate the bug.

Thanks!

**Comment by Cvar1984** [comment]
> Not sure exactly what you're trying to do, but try creating a unique instance for each image. Reusing the same image resource is probably causing the weirdness you're seeing.
> 
> If you're submitting a bug report, please provide a minimal test case to clearly demonstrate the bug and I'll reopen.
> 
> Thanks!

Yes, i think using the same resource is causing bizzare result when i try to overaly
