### ISSUE TITLE
Change toString() method name because it fails with __call() proxy?

### ISSUE THREAD

**Issue by pwFoo** [claviska/SimpleImage#256]
Hi,
I tried to use SimpleImage with an very basic proxy class based on "__call()" and it fails to execute toString(), because it's named like the magic method "__toString()", which fired instead of `__call("toString", $args")`. I know that could be handled by the proxy / custom class, but would be great to keep the proxy without additional logic to handle such things.

Is there a way around that (another method to get the image string) or would it possible to rename that function in the SimpleImage project?

**Comment by claviska** [comment]
I'm not interested changing the API anytime soon, as the library is very stable and this would be a breaking change. Perhaps the logic in the proxy could be more generic to support any library that supplies its own `toString` method.

Another thing you could do is extend the SimpleImage class and add your own alternative to `toString`, which is [a really simple method](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L360-L371).

I hope that helps!

**Comment by pwFoo** [comment]
Hi @claviska,
thanks for response. I don't know if `toString()` really is needed, because of `toFile()` (save to file first) and `toDataUri()` (use with IMG tag as data)...
So maybe I just not use `toString()` or use SimpleImage class to extend a custom class which adds an alternative method name for it.

Great project! Thanks for sharing it! 👍

**Comment by pwFoo** [comment]
Another way around... `_call('proxy')` returns SimpleImage object reference to work with and optional enable "ProxyChaining" (first call returns SimpleImage object instead of proxy object) to change proxy method chaining to SimpleImage chaining. 
So all fine for me.
