### ISSUE TITLE
imagecreatefrombmp requires PHP >= 7.2

### ISSUE THREAD

**Issue by marebe1602** [claviska/SimpleImage#259]
the readme.md still says, that minimum PHP version is 5.6, but imagecreatefrombmp requires at least 7.2.
Maybe there should be a version check added, or the minimum requirement in readme has to be changed...
[Docs](https://www.php.net/manual/de/function.imagecreatefrombmp.php)

**Comment by claviska** [comment]
Good catch. It was added in this PR: https://github.com/claviska/SimpleImage/pull/242/commits/8aa5e71758cc9424098e15ae1dc2c67805e636bf

There should be a function check to make sure the required functions exists. The rest of the library still works fine on older PHP versions.

**Comment by marebe1602** [comment]
My phpStorm hinted me that problem. I always set the PHP-Version, phpStorm should check against to the minimum required specs of the project.
Solution sounds good.
...and thanks for that great tool!
