### ISSUE TITLE
Add AVIF support

### ISSUE THREAD

**Issue by S1SYPHOS** [claviska/SimpleImage#260]
Hey there,
AVIF support would be great! I will edit this issue later to include more information, if you wish.

Cheers,
S1SYPHOS

**Comment by claviska** [comment]
I’d love to see this too. Support would first have to be added to the [GD library](https://libgd.github.io/) and then adopted by PHP, so I would first check there to make sure this has been requested upstream as well.

**Comment by S1SYPHOS** [comment]
True, see the related topics over at [libgd](https://github.com/libgd/libgd/issues/557) & [Intervention](https://github.com/Intervention/image/issues/891).

**Comment by distantnative** [comment]
@claviska seems like it has made it into libgd now: https://github.com/libgd/libgd/releases/tag/gd-2.3.2

And if this is accurate PHP included support from 8.1 upwards: https://php.watch/versions/8.1/gd-avif

**Comment by claviska** [comment]
I would accept a PR that provides this as long as it's backwards compatible with 7.x as well.
