### ISSUE TITLE
Webp not supported

### ISSUE THREAD

**Issue by Mxater** [claviska/SimpleImage#271]
This is not soported.

In line 131
```
        // Get image info
        $info = getimagesize($file);
        if($info === false) {
            throw new \Exception("Invalid image file: $file", self::ERR_INVALID_IMAGE);
        }
        $this->mimeType = $info['mime'];
```
This throw false, because **getimagesize** dont support webp [https://www.php.net/manual/es/function.getimagesize.php](url)
With **WEBP** images, show false Exception.

I tested in PHP 7.0 and 7.3

 #173

**Comment by claviska** [comment]
webp was added to `getimagesize()` in 7.1.0 [per the PHP docs](https://www.php.net/manual/en/function.getimagesize.php#refsect1-function.getimagesize-changelog). It isn't expected to work in 7.0 but should be working in 7.3 if your version of PHP/gd has webp enabled.
