### ISSUE TITLE
Paints the inner part of the ellipse and not just the thickness of the border

### ISSUE THREAD

**Issue by matheusjohannaraujo** [claviska/SimpleImage#272]
In version 3.6, when using the ellipse method with a thickness greater than 1, the image disappears (becomes transparent).

In version 3.5 it works normally!

<hr>

The problem is on line 1447: $tempColor = $tempImage->allocateColor($tempColor);

Switching to $tempColor = $tempImage->allocateColor("#000000"); the problem is solved!

**Comment by claviska** [comment]
@maPer77 do you have time to take a look at this?

**Comment by maPer77** [comment]
> In version 3.6, when using the ellipse method with a thickness greater than 1, the image disappears (becomes transparent).
> 
> In version 3.5 it works normally!
> 
> The problem is on line 1447: $tempColor = $tempImage->allocateColor($tempColor);
> 
> Switching to $tempColor = $tempImage->allocateColor("#000000"); the problem is solved!


Can you post the code you are using to draw the ellipse?

**Comment by matheusjohannaraujo** [comment]
<?php

try {
  require_once "vendor/autoload.php";
  $image = new \claviska\SimpleImage('https://miro.medium.com/max/1838/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg');
  $x = 100;
  $y = 100;
  $width = 100;
  $height = 100;
  $color = "#FF0000";
  $thickness = 5;// Change the value to 1 and see the difference
  $image->ellipse($x, $y, $width, $height, $color, $thickness);
  $mimeType = "image/png";
  $quality = 100;
  $image->toScreen($mimeType, $quality);
} catch(\Exception $err) {
  echo $err->getMessage();
}

?>

**Comment by matheusjohannaraujo** [comment]
<?php

try {
  require_once "vendor/autoload.php";
  $image = new \claviska\SimpleImage("https://miro.medium.com/max/1838/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg");
  $x = 100;
  $y = 100;
  $width = 100;
  $height = 100;
  $color = "#FF0000";
  $thickness = 5;// Change the value to 1 and see the difference
  $image->ellipse($x, $y, $width, $height, $color, $thickness);
  $mimeType = "image/png";
  $quality = 100;
  $image->toScreen($mimeType, $quality);
} catch(\Exception $err) {
  echo $err->getMessage();
}

?>

**Comment by matheusjohannaraujo** [comment]
```php
<?php

try {
  require_once "vendor/autoload.php";
  $image = new \claviska\SimpleImage("https://miro.medium.com/max/400/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg");
  $x = 200;
  $y = 120;
  $width = 60;
  $height = 60;
  $color = "#FF0000";
  $thickness = 5;// Change the value to 1 and see the difference
  $image->ellipse($x, $y, $width, $height, $color, $thickness);
  $mimeType = "image/png";
  $quality = 100;
  $image->toScreen($mimeType, $quality);
} catch(\Exception $err) {
  echo $err->getMessage();
}

?>
```

**Comment by matheusjohannaraujo** [comment]
The image disappears when using the ELLIPSE method along with other methods of the SimpleImage class

**Comment by maPer77** [comment]
ok, change the color from `$color = "#FF0000";` to `$color = "red";`
This should resolve until I change the code to accept `#FF0000`

**Comment by maPer77** [comment]
Let me know if it solved the problem.

**Comment by matheusjohannaraujo** [comment]
Hello how are you. Answering your question: Yes, it partially solves it!

 I built an image processing system using SimpleImage that has a graphical interface to use the methods of the classes and tals ... changing from hexadecimal to solid color is not intuitive for an input [type = color], I will continue for while using version 3.5

Good work for you, partner, I just reported the bug so you can be aware! You don't have to worry about me, as I also develop libraries and frameworks and I know how hard it is to support the tool.

I know very little English, the writing can be strange lol. I am Brazilian.

**Comment by maPer77** [comment]
@matheusjohannaraujo This change should work.
If you want to test before the commit is accepted, you can get the changed file at: https://github.com/maPer77/SimpleImage
I also speak Portuguese, if you want to add me to the dircord ... maPer77

**Comment by matheusjohannaraujo** [comment]
Oi, tudo bem. Não te achei no Discord, acho que é pq não sei mexer direito nql rsrsrs...
Fiz esse código aí para testar as cores na classe SimpleImage. Eu deixei somente a parte de hexadecimal, eu testei com o array com o rgba e tá OK!

```php

<?php

try {
  function decToHex(int $val) :string {
    switch($val) {
      case 10: return "A";
      case 11: return "B";
      case 12: return "C";
      case 13: return "D";
      case 14: return "E";
      case 15: return "F";
    }
    return (string) $val;
  }
  $autoload = file_get_contents("https://raw.githubusercontent.com/maPer77/SimpleImage/master/src/claviska/SimpleImage.php");
  $autoload = substr($autoload, strpos($autoload, "<?php") + strlen("<?php"));
  eval($autoload);
  $image = new \claviska\SimpleImage("https://miro.medium.com/max/600/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg");
  $x = 300;
  $y = 170;
  $width = 60;
  $height = 60;
  $thickness = 5;
  $sinalA = rand(-1, 0) == 0 ? 1 : -1;
  $sinalB = rand(-1, 0) == 0 ? 1 : -1;
  for ($i = 0; $i <= 255; $i+=5) {    
    $color = "#" . decToHex(rand(0, 15)) . decToHex(rand(0, 15)) . decToHex(rand(0, 15)) . decToHex(rand(0, 15))  . decToHex(rand(0, 15)) . decToHex(rand(0, 15));
    $image->ellipse(
      $x + $i * $sinalA,
      $y + $i * $sinalB,
      $width + $i,
      $height + $i,
      $color,
      ($thickness + $i) / 5
    );
  }
  $image->toScreen("image/jpeg", 100);
} catch(\Exception $err) {
  echo $err->getMessage();
}
```

**Comment by maPer77** [comment]
In reality, the problem only occurred with the pure red color "#ff0000", because the ellipse is made with 2 filled ellipses and at the end of the process this color was used to exclude the central ellipse.
It was done this way because the native code of the GD library has problems. #269

**Comment by matheusjohannaraujo** [comment]
OK, if I find any more bugs I will report!

**Comment by maPer77** [comment]
Thanks for testing :+1:

**Comment by matheusjohannaraujo** [comment]
The image processing system that I had talked about.

https://img-edt.herokuapp.com

**Comment by maPer77** [comment]
Cool
