### ISSUE TITLE
new feature textBox bug

### ISSUE THREAD

**Issue by webooindia** [claviska/SimpleImage#282]
when we use **textBox** with anchor  bottom it not automatic center as in **text** function 

Please guide 
anchor (string) - The anchor point: 'center', 'top', 'bottom', 'left', 'right', 'top left', 'top right', 'bottom left', 'bottom right' (default 'center').

**Comment by maPer77** [comment]
Can you post the code you are using and an image of how the text looks?

**Comment by claviska** [comment]
Closing as no-response. I'm happy to reopen this if you can provide a minimal repro.
