### ISSUE TITLE
Update required php version

### ISSUE THREAD

**Issue by mtwango** [claviska/SimpleImage#283]
Since **resolution()** method uses [imageresolution](https://www.php.net/manual/en/function.imageresolution.php) function, which is in GD library from PHP version 7.2, I would suggest upgrading your composer.json.

The reason is to prevent users from using this method on lower PHP versions.

**Comment by claviska** [comment]
Good catch. Let's track this in #284 as part of the larger 4.0 release to phase PHP 5.x out.
