### ISSUE TITLE
PHP 8.1 deprecation warning

### ISSUE THREAD

**Issue by distantnative** [claviska/SimpleImage#287]
Using it with PHP 8.1 throws the following deprecation warning

```
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated
```

for `claviska/simpleimage/src/claviska/SimpleImage.php:61`

**Comment by skiphog** [comment]
And also
imagecreatetruecolor();
`Deprecated: Implicit conversion from float to int loses precision in claviska/SimpleImage.php on line 805`

imagecopyresampled()
`Deprecated: Implicit conversion from float to int loses precision in claviska/SimpleImage.php on line 816`

And maybe somewhere else

**Comment by claviska** [comment]
Thanks for reporting this. And thanks, @maPer77, for submitting the patch!

**Comment by maPer77** [comment]
> Thanks for reporting this. And thanks, @maPer77, for submitting the patch!

:+1:
