### ISSUE TITLE
3.6.4 doesn't include fix commit

### ISSUE THREAD

**Issue by distantnative** [claviska/SimpleImage#291]
It looks like the 3.6.4 tag/release does not actual include the fixing commit it references:
<img width="538" alt="Screen Shot 2021-12-04 at 11 34 40" src="https://user-images.githubusercontent.com/3788865/144706402-558a51b9-48ab-4cf2-91db-cb8da0ce7952.png">
<img width="1275" alt="Screen Shot 2021-12-04 at 11 34 47" src="https://user-images.githubusercontent.com/3788865/144706404-2932987d-bcb6-4d13-816b-f483d0319f2e.png">

Indeed, when downloading the ZIP, you can also see that the fixes are missing (e.g. still `null` as parameter default of `__construct`).

**Comment by claviska** [comment]
Thanks for catching this. Try [3.6.5](https://github.com/claviska/SimpleImage/releases/tag/3.6.5).
