### ISSUE TITLE
A feature to fit image in a fixed canvas size with blur background of original image.

### ISSUE THREAD

**Issue by Aatish124** [claviska/SimpleImage#294]
Can you please add a feature to fit image in a fixed canvas size with blur background of original image ? something like this image (https://i.stack.imgur.com/b4pDj.jpg)

**Comment by claviska** [comment]
You can do this with:

```php
$bottom = new \claviska\SimpleImage();
$top = new \claviska\SimpleImage();

$top
  ->fromFile('parrot.jpg')
  ->bestFit(400, 600)
  ->border('white', 8);

$bottom
  ->fromFile('parrot.jpg')
  ->autoOrient()
  ->blur('gaussian', 40)
  ->overlay($top)
  ->toScreen();
```

Result:

![example](https://user-images.githubusercontent.com/55639/148389950-d6871895-ee6f-4ec4-913a-e6054c7d8191.jpg)

**Comment by Aatish124** [comment]
sorry i want to fit the image in square image like instagram. here are few ref. images :
![vertical](https://user-images.githubusercontent.com/22254522/148410264-bedb7af7-634e-49e3-8d00-8b5700d91451.jpg)
![horizntl](https://user-images.githubusercontent.com/22254522/148410268-302b30ff-02c0-4ebf-adcb-bfd749b13469.jpg)
 I hope u understood the requirement of output
