### ISSUE TITLE
How to different font file & size, but in an equal position with center align

### ISSUE THREAD

**Issue by dandyraka** [claviska/SimpleImage#303]
Hello, anyone can help me how can I do this
![image](https://user-images.githubusercontent.com/18587059/177799877-d93d239f-5815-4f57-b340-ab5eee65a49c.png)

Two different font file & size, but in an equal position with center align just like the pic.

Thank you.

**Comment by edutrul** [comment]
I had this issue with 
<img width="716" alt="image" src="https://user-images.githubusercontent.com/1582129/236589102-52ca23b2-a8b0-483b-99ff-b403a9fccbe8.png">


I am sending a PR shortly.

**Comment by claviska** [comment]
Fixed in #321

**Comment by edutrul** [comment]
Thank you.
