### ISSUE TITLE
Imagick magick support

### ISSUE THREAD

**Issue by shadowx-jb** [claviska/SimpleImage#308]
Would it be possible to implement imagick magick support into the code?

Thank you

**Comment by claviska** [comment]
Thanks for the suggestion. Unfortunately, this library was developed specifically to make using GD easier and solve some of the quirks I've run into over the year. ImageMagick/GraphicsMagick are very different beasts with a much larger feature set (but also a steeper curve to install) and, while I agree that having a similar API for it would be very nice, I'm personally not interested in building or maintaining that.

I encourage anyone who is interested in doing this to use SimpleImage's API for inspiration. 😄
