### ISSUE TITLE
Nothing working

### ISSUE THREAD

**Issue by KarlosFanta** [claviska/SimpleImage#314]
Hi.
I ran http://localhost:8080/whiteboard/example/index.php
and it only shows the parrot. No editing/drawing options.
PHP 7.3.1
any browser on W10, wampserver.

**Comment by claviska** [comment]
SimpleImage isn't an editor, but a PHP library you can used to manipulate images using GD. The example file will show just the image. You can edit the file itself and refresh the page to preview changes:

https://github.com/claviska/SimpleImage/blob/master/example/index.php

If I've misunderstood something, let me know.
