### ISSUE TITLE
Implicit conversion from float 684.8547008547008 to int loses precision

### ISSUE THREAD

**Issue by distantnative** [claviska/SimpleImage#317]
Receiving this error with 4.0.0

```
Implicit conversion from float 684.8547008547008 to int loses precision
```

pointing to https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L986

My hunch would be that https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L975 also should be wrapped in `(int) round ()`, same as already done in https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L970

**Comment by claviska** [comment]
Fixed in #318

**Comment by distantnative** [comment]
@claviska thank you! unfortunately the 4.0.1 tag seems to not include the fix

**Comment by claviska** [comment]
Sorry about that. I goofed and created the tag prematurely. 4.0.2 fixes that!
