### ISSUE TITLE
getExif(): Return value must be of type ?array, bool returned

### ISSUE THREAD

**Issue by crazy-weasel** [claviska/SimpleImage#323]
Hi!

With the PHP8 upgrade of the library and the introduction of return value type declarations, the [getExif](https://github.com/claviska/SimpleImage/blob/a447473883e5dd0daa0d014ae849f0db5b8a1d08/src/claviska/SimpleImage.php#LL586C38-L586C38)-method can cause an error if the exif_read_data-function, that populates the property, returns false.

The return value type declaration should be changed to `array|bool|null` or the handling of the return value should reflect the possibility of the value false.

Greetings,
Alex

**Comment by claviska** [comment]
Thanks, that makes sense. Anyone want to take a stab at a PR?
