### ISSUE TITLE
Underlay or Border

### ISSUE THREAD

**Issue by expertlearner** [claviska/SimpleImage#38]
Hi, it's a New Feature request. I need to bestfit all images to 800x500 but also to make their size 800x500 by adding white space where it's needed. I mean, every image proportion is different to the final size and I need to keep it, so, an 1600x700 image after bestfit(800,500) is going to be 800x350. In order to make it 800x500 I need to add 150px of white on the sides, 75 white on the left and 75 white on the right, so it ends 800x500 keeping proportion.

It can be "underlay" but because the current image can be different to png it doesn't work, so, what about "border", something like border(img,A,B,#color,center center) where the image keeps it's size but grows up to AxB with #color around?

**Comment by bloxcms** [comment]
In your last code:
`$background->create($max_width, $max_height, '#fc0');`
I have changed '#fc0' to [0,0,0,127] , i.e. transparent background.
This works for PNG overlays, but for JPGs it gives black background.
