### ISSUE TITLE
Black background on PNGs with transparency

### ISSUE THREAD

**Issue by godbout** [claviska/SimpleImage#40]
Hi,

I like the class! But it works strangely in some cases for me.
If I rotate to something other than 90, 180, or 270, the generated (need) background is back, not transparent. Is there a way to make it transparent?

Examples:
90 rotate
![this_is_tomorrow_tuesday_which_doesnt_make_any_sense___dailycuckoo](https://f.cloud.github.com/assets/121373/2417823/d4a0c892-ab2b-11e3-84ce-e7283091ec1d.jpg)

95 rotate
![this_is_tomorrow_tuesday_which_doesnt_make_any_sense___dailycuckoo](https://f.cloud.github.com/assets/121373/2417827/eb5cee3a-ab2b-11e3-8617-7d3254274b8e.jpg)

It happens also with some other methods that have to add some background.

**Comment by claviska** [comment]
I'm 99% sure this is an issue with GD. The `rotate()` method in SimpleImage is pretty straightforward, so there's not much we can do to fix this. It should probably be filed as a bug in the GD library.
