### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by claviska** [claviska/SimpleImage#46]
This is something I've been meaning to get around to. The library itself is pretty handy, but having inadequate documentation will limit its reach. I'd love to get a little mini-site setup with better usage/examples.

**Comment by ollakalla** [comment]
i have a problem with Arabic names, when i try to convert it it gives me an error
[function.getimagesize]: failed to open stream
Invalid image: images/4edd5_?????_?????????.jpg
i think i need to add "UTF", but i don't where to add it to fix this error
thank you for this great library

**Comment by claviska** [comment]
Sounds like a PHP issue. [This may help](http://stackoverflow.com/questions/1525830/how-do-i-use-filesystem-functions-in-php-using-utf-8-strings). Hope it works for you!

**Comment by kulander** [comment]
Hi claviska.
What about special characters as text "inside" the generated image (not the filename)? I have used both utf8_decode/utf8_encode but no success so far.

**Comment by claviska** [comment]
Make sure the font supports the characters you're trying to use. GD doesn't seem to fallback to other fonts (like the OS) when a glyph is missing.

**Comment by kulander** [comment]
So true claviska, I forgot to state my solution: like advised, by replacing the font with one that supports special characters, the problem was solved.
Thanks a lot!

**Comment by claviska** [comment]
Better docs are included in the readme in 3.0.
