### ISSUE TITLE
Feature request - $left and $top parameters in Thumbnail function

### ISSUE THREAD

**Issue by TellCVickers** [claviska/SimpleImage#67]
I'm probably posting this in the wrong place; my apologies if so. 

I've added $left and $top parameters to thumbnail() that allow for custom positioning of thumbnails. For the purposes of the software I work on, I set the parameters both to 0 (captures top of image and crops vertical overflow below the width of the thumbnail). Here's my new version of thumbnail():

	function thumbnail($width, $height = null, $left=null, $top=null) {

		// Determine height
		$height = $height ?: $width;

		// Determine aspect ratios
		$current_aspect_ratio = $this->height / $this->width;
		$new_aspect_ratio = $height / $width;

		// Fit to height/width
		if ($new_aspect_ratio > $current_aspect_ratio) {
			$this->fit_to_height($height);
		} else {
			$this->fit_to_width($width);
		}
		if(is_null($left)){
			$left = floor(($this->width / 2) - ($width / 2));
		}
		if(is_null($top)){
			$top = floor(($this->height / 2) - ($height / 2));
		}	

		// Return trimmed image
		return $this->crop($left, $top, $width + $left, $height + $top);

	}	

Not sure if others would find this useful, but I wanted to pass it along regardless. In any case, thanks for your work on SimpleImage; it makes my life much, much easier on a regular basis.

**Comment by claviska** [comment]
Just curious, why not crop it after?

```php
$image->thumbnail(...)->crop(...)->save(...);
```

**Comment by TellCVickers** [comment]
Thanks for getting back to me so quick! Looking back, I wasn't too clear about what I was trying to get across; my concern isn't so much about cropping (the function as-is handles my needs perfectly), but for the application I'm working on, I need to start capturing the thumbnail at the 0,0 x/y coordinates of the source image; the function as originally written was capturing the thumbnail from just shy of halfway down through the image. It just turned out I needed a bit of a specialized version of the thumbnail function which just captures from the top of the image. Other than that, the thumbnail function did exactly what I needed. With that said, I'm not sure how many others would find it useful, but I figured I'd send it along anyway. I should also note that I haven't tested this very thoroughly yet, but so far it's doing exactly what I need. Let me know if you have any questions.

**Comment by claviska** [comment]
Gotcha...it could probably be done with a bit of calculations, but I see where it could be a handy shortcut.

**Comment by TellCVickers** [comment]
Yeah, there's most likely a better way to go about it, for sure. Anyway, feel free to do with it as you like!

**Comment by McSodbrenner** [comment]
Hi,
I needed the same and did it this way.
`$top_or_left` is a float between 0 and 2. 1 would be the default crop position as it is now. 0 would be "crop from top" and 2 would be "crop from bottom". Just added the code below `// respect start position in percent`.

~~~
function thumbnail($width, $height = null, $top_or_left = null) {

	// Determine height
	$height = $height ?: $width;

	// Determine aspect ratios
	$current_aspect_ratio = $this->height / $this->width;
	$new_aspect_ratio = $height / $width;

	// Fit to height/width
	if ($new_aspect_ratio > $current_aspect_ratio) {
		$this->fit_to_height($height);
	} else {
		$this->fit_to_width($width);
	}
	$left = floor(($this->width / 2) - ($width / 2));
	$top = floor(($this->height / 2) - ($height / 2));

	// respect start position in percent
	if ($top_or_left !== null) {
		if ($new_aspect_ratio > $current_aspect_ratio) {
			$left = floor($left * $top_or_left);
		} else {
			$top = floor($top * $top_or_left);
		}
	}

	// Return trimmed image
	return $this->crop($left, $top, $width + $left, $height + $top);
}
~~~
