### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by babeuloula** [claviska/SimpleImage#71]
Hello, 

When I resize a PNG with a transparent background, then I save it on JPG, the backgorund is black.
How I can make a white background ?

Thanks

**Comment by claviska** [comment]
That's the default color that GD uses for whatever reason. Off the top of my head, I don't think it can be changed, but this should work as an alternative:

```php
// Your image
$img = new SimpleImage('your-image.png');

// Create an image with the same dimensions and desired color
$bg = new SimpleImage(null, $img->get_width(), $img->get_height(), '#fff');

// Overlay the PNG onto the background image
$bg->overlay($img);

// Save the JPEG
$bg->save('result.jpg');
```

Not tested, but you get the idea. Would love to know if it works for you.
