### ISSUE TITLE
Loss of Quality

### ISSUE THREAD

**Issue by johoehn** [claviska/SimpleImage#74]
Hey,
I am saving a .jpg image with a width of 1700px:

$img->fit_to_width(1700)->save($new_file, 100);

Even though quality is set to 100, the result is very blurred. 
Do you have any idea what could be the reason/a solution?
Thanks!

**Comment by claviska** [comment]
Could be the resampling that happens in the `resize()` method. Need to see the image to know for sure.

**Comment by claviska** [comment]
Also, is the original image bigger or smaller than 1700px? There would be obvious quality loss if the image was smaller, otherwise it shouldn't be too bad.

For further consideration, please attach the image in question so we can test it out :)
