### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jawadsahil** [claviska/SimpleImage#78]
This is so nice class.

May be this feature is already present and I am not able to find it from documentation.

I just need to show error image instead of text as in following code:

```php
try {
    $img = new SimpleImage('image.jpg');
    $img->flip('x')->output();

} catch(Exception $e) {
    $img = new SimpleImage(null, 200, 100, '#000');
    $img->text('Error: ' . $e->getMessage())->output();
}
```
So basically I am asking to add a feature to **add a function to convert text to image** (using any default font) without a need of an existing image file. I am doing it now in this way, but it would be better if the class have such a function.

```php
} catch(Exception $e) {
	header('Content-Type: image/jpeg');
	$im = imagecreatetruecolor(200, 100);
	$text_color = imagecolorallocate($im, 180, 180, 180);
	imagestring($im, 1, 5, 5,  'Error: ' . $e->getMessage(), $text_color);
	imagejpeg($im);
	imagedestroy($im);
}

**Comment by claviska** [comment]
Specify a format for `output` and set the color (defaut is black):

```php
try {
    $img = new SimpleImage('butterfly.jpg');
    throw new Exception('Nope');
    $img->flip('x')->output();
} catch(Exception $e) {
    $img = new SimpleImage(null, 200, 100, '#000');
    $img->text('Error', 'delicious.ttf', 12, '#fff')->output('jpg');
}
```
