### ISSUE TITLE
How to resize image and save a square image?

### ISSUE THREAD

**Issue by vandung2k6** [claviska/SimpleImage#79]
Hi You,

I have a image (400 * 800 or any size) . How to resize to 800 * 800 ?
width = 400px;
height = 800px;

New  image have background = white and old image is center and width = width + 400px;

Thanks so much.

**Comment by claviska** [comment]
Take a look at the resize method:

```php
$img = new SimpleImage('your-image.jpg');
$img->resize(800, 800);
```

If you need more detailed assitance, please submit your question on StackOverflow. This is for bug reports and project contributions, not troubleshooting and integration. Thanks.
