### ISSUE TITLE
36 Megapixel image causes gd-png error: cannot allocate image data

### ISSUE THREAD

**Issue by ZaneCEO** [claviska/SimpleImage#81]
Hello, I'm trying to integrate your class into a project where I've to work with some pretty big files.

The following code tries to resizes the $path image (32 bit PNG, ~11.000 pixel) to a 1000x1000 image:

````
$path="https://s3.eu-central-1.amazonaws.com/dw-uploads/photos/originals/3bd39e9fa22678933c7b7427237a715a";
$fs="test_local.png";

file_put_contents($fs, file_get_contents($path));

require_once '/home/simpleimage/SimpleImage.php';
$img = new abeautifulsite\SimpleImage($fs);
$img->best_fit(1000, 1000)->save($fs);
```

But fails with this error:

`Parse error: imagecreatefrompng(): gd-png error: cannot allocate image data in /home/simpleimage/SimpleImage.php on line 1105`

Even if the whole thing [should require less than 256MB](http://www.dotsamazing.com/en/labs/phpmemorylimit), my php.ini has `memory_limit = 512M`.

The main bugreport is: I think your class should throw an exception for this

Second bug: this smells like multiple object are being created. Could you please look into it?

Thanks!

**Comment by claviska** [comment]
It's not a memory leak. The GD library is notorious for using a lot of memory. Depending on your server, even 2-3MB images can throw that error.




It's also not something we can catch: http://stackoverflow.com/questions/2318858/how-to-recover-from-a-fatal-error-allowed-memory-size-exhausted




Normally you could just bump up the memory for PHP, but for gigantic images like that you may need to seek an alternative solution to GD. ImageMagick, for example—although I'm not sure it handles memory better when run as a PHP module.






— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net

**Comment by sexyzane** [comment]
acknowledged, thanks for your reply and explain!
