### ISSUE TITLE
Confirm images are loaded before throwing exception

### ISSUE THREAD

**Issue by mrshaikh** [claviska/SimpleImage#82]
I am loading images from url's which are not being fully loaded and exception of "Invalid Image" are thrown.
Is there anyway to verify image is loaded before validation?

Thanks for you time.

**Comment by claviska** [comment]
After you load the image (and before you access it with SimpleImage), you can use getimagesize() to determine if the image is valid. It will return false on failure, and for deeper checks you can look at the resulting mime type.





— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net
