### ISSUE TITLE
Images flip

### ISSUE THREAD

**Issue by osCMattiFinn** [claviska/SimpleImage#85]
When using fit_to_width() images rotate anticlockwise 90 degrees.  Not good.

$img = new SimpleImage(DIR_FS_IMAGES . $filename);
$img->fit_to_width(250)->save(DIR_FS_IMAGES . '250_' . $filename);
$img->fit_to_width(100)->save(DIR_FS_IMAGES . '100_' . $filename);
$img->fit_to_width(50)->save(DIR_FS_IMAGES . '50_' . $filename);

Original image is 2448px x 3264px

**Comment by osCMattiFinn** [comment]
As I understand it, your class should use exif_read_data() to make sure the image is oriented correctly:

http://php.net/manual/en/function.exif-read-data.php#76964

I resaved the image using Irfanview and now the image is correctly oriented after resize using fit_to_width().

**Comment by claviska** [comment]
You need to use the `auto_orient()` method to fix images saved with a different orientation. It will not happen automatically.

**Comment by osCMattiFinn** [comment]
Don't you think that the class should itself use $this->auto_orient()?

I think it should happen automatically, this is why we use classes for specific purposes.

**Comment by claviska** [comment]
Not really. The class isn't just for loading existing images, and it supports formats other than JPG as well. More importantly, the `auto_orient()` method does a rotation that may not be desirable on large images where PHP doesn't have enough memory to handle it. Best to give the developer the option.

If you prefer to use it, just chain it. A few extra characters won't bloat your code.

**Comment by osCMattiFinn** [comment]
So I tried the following:

$img->fit_to_width(100)->auto_orient()->save(DIR_FS_IMAGES . '100_' . $filename);

and:

$img->auto_orient()->fit_to_width(100)->save(DIR_FS_IMAGES . '100_' . $filename);

Didn't work!

**Comment by claviska** [comment]
The `auto_orient()` method has been tested and works fine. Chances are, your original image doesn't have the correct EXIF data. Closing since this is an implementation issue, not an issue with the library.
