### ISSUE TITLE
Resize from left/top

### ISSUE THREAD

**Issue by vespino** [claviska/SimpleImage#87]
Is it possible to resize an image from the left/top position instead of center/middle?

**Comment by claviska** [comment]
Resize simply shrinks or expands the full image. Are you looking for the crop method instead?






— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net

**Comment by vespino** [comment]
I'm using the class to make splashscreens for mobile apps. I create a design, 2560x1440 pixels, and automate the process of creating a dozen other sizes. Most of these sizes have other ratios so parts of the design are cut off. By setting the point which is cu toff (top or bottom) I'm hoping to be able to control which part is cutoff. Now the top and bottom are cut off, I'm hoping to cut the image on one side only.

**Comment by claviska** [comment]
Nothing will do that out of the box. You'd have to do the math yourself or perhaps find a clever way to use trim/best_fit along with resize.
