### ISSUE TITLE
Overlay image is masking target image

### ISSUE THREAD

**Issue by jmarus** [claviska/SimpleImage#88]
I'm trying to overlay an uploaded image onto an existing image, in my case, a jersey crest on top of a jersey. Here's the code I'm using:

    $jersey = new abeautifulsite\SimpleImage($jerseyPath);
    $jersey->overlay($resizePath, 'top left', 1, 348, 120)->save($mergedJerseyPath);

The result looks like the attached image: 
<img width="572" alt="screenshot 2015-07-23 14 49 39" src="https://cloud.githubusercontent.com/assets/656149/8863036/12be57c0-314a-11e5-9a9d-d861dab7f72d.png">

**Comment by claviska** [comment]
Cool idea. Would you care to leave the two source images so I can try this locally?

**Comment by jmarus** [comment]
![hammerheads-logo](https://cloud.githubusercontent.com/assets/656149/8863099/884ffc6e-314a-11e5-8071-042c1d1ffa82.png)
![ana-home](https://cloud.githubusercontent.com/assets/656149/8863111/a13a4b12-314a-11e5-8fc4-f5f4d14274d8.png)

**Comment by jmarus** [comment]
I'm first resizing the crest (the shark), then applying it to the jersey. Love your library. I've been messing around with regular ol' GD and your library is so GD better ;)

**Comment by jmarus** [comment]
I'm also noticing that it may be blending alphas of the two images as well, so the colour of the crest changes depending on which jersey you select.

**Comment by claviska** [comment]
This is weird. Do you know how these PNGs were created? I resaved both of them in Photoshop and then it worked fine.

**Comment by jmarus** [comment]
They were pulled down from the web. I could try re-saving them all. The source crest image was saved from Photoshop. 

When you re-saved, you didn't have any masking issues or incorrect colours?

**Comment by claviska** [comment]
Nope, looked like this (I did change the offsets a bit so it was easier to see).

![result](https://cloud.githubusercontent.com/assets/55639/8863689/dccc02ec-3168-11e5-815e-05ed45617aff.png)

**Comment by jmarus** [comment]
You are a masterful genius. Who knew it could be so simple? I've reserved all the PNGs from Photoshop and they now work great. Now I just have to crop the top jersey out of the two jersey image, and we're off to the races. 

Where can I send tips/donation?

**Comment by claviska** [comment]
Could be some bad data in the image or even something that GD doesn't like. Glad it's working for you now :)



​

​I don't have a donation button anymore, but if you feel obliged then my PayPal email is cory at abeautifulsite.net.

**Comment by jmarus** [comment]
Closing this due to broken PNG files. Thanks Cory :)
