### ISSUE TITLE
Add Stroke to Text

### ISSUE THREAD

**Issue by jmarus** [claviska/SimpleImage#90]
Would love to be able to apply a X side border of #XXXXXX to overlayed text. 

In my case, a 1px black border.

Cory, here's the link you sent me. Not sure I'm capable of adding it myself :)

http://stackoverflow.com/questions/26905271/how-to-give-border-to-text-in-php-gd-library

**Comment by claviska** [comment]
Added in the latest release. See [last two arguments for text()](https://github.com/claviska/SimpleImage/blob/master/src/abeautifulsite/SimpleImage.php#L963) for details.
