### ISSUE TITLE
Issue with High Resolution Images over 12573px X 9264px (10MB)

### ISSUE THREAD

**Issue by pankajpragma** [claviska/SimpleImage#91]
Hi,

SimpleImage class works great and I am using this since long time.
I would like to report a bug you may like to fix in next release.

It doesn't resize image over 12573px x 9264px (10MB)

Example:
$img_resize = new SimpleImage();
$img_resize->load($temp_path)->best_fit(800, 800)->save($path);

Test Case to regenerate issue:
http://www.eastboca.net/EuroPan/EuroPanaFiles/EuroPanGroupPhoto_10_MB.jpg

Thank you!

**Comment by claviska** [comment]
This is probably a PHP memory limit.

**Comment by claviska** [comment]
To clarify, the GD library uses a lot of memory for image processing. Large images can easily hit PHP's memory limit. The only solution is to bump the limit on your server. You can try something like this:

```php
ini_set('memory_limit', '32M');
```
