### ISSUE TITLE
multiple color text?

### ISSUE THREAD

**Issue by prnty** [claviska/SimpleImage#92]
Is there a way to have one script with two different colors of text

example: 
NAME HERE: TITLE

"NAME HERE:" is dynamic text and needs to be one color, "TITLE:" is also dynamic text and needs to be a different color.

Know of any solutions that i can use with your class?

**Comment by claviska** [comment]
You'd have to use the text() method twice and somehow calculate the width of the text box. GD isn't that great with handling text, so it's something we can improve on.

**Comment by claviska** [comment]
This is available now. See 32389d9.
