### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by hectorbarranca** [claviska/SimpleImage#93]
If you use special characters like "á" or its code "&aacute ;" it is not recognized.

**Comment by claviska** [comment]
Does the font you're using support those characters?

**Comment by hectorbarranca** [comment]
Thanks my friend, I am using the delicious.ttf included in the example, I opened it and it has this characters

**Comment by hectorbarranca** [comment]
Sorry my friend, I use another font more common (Arial) and it works jeje
