### ISSUE TITLE
Unsupported format when uploading file

### ISSUE THREAD

**Issue by w4r0** [claviska/SimpleImage#94]
The class throwing an exception:

    Fatal error: Uncaught exception 'Exception' with message 'Unsupported format' in D:\wamp\system\vendors\abeautifulsite\SimpleImage.php on line 901

when I tried to resize tmp upload file. Here's my code:

    $image = new abeautifulsite\SimpleImage($_FILES['uploadfile']['tmp_name']);
    $image->fit_to_width(1000);
    $image->save($_FILES['uploadfile']['tmp_name']);

and here's my $_FILES array:

    array (size=1)
      'uploadfile' => 
           array (size=5)
           'name' => string 'IMG_98891.jpg' (length=13)
           'type' => string 'image/jpeg' (length=10)
           'tmp_name' => string 'C:\Windows\Temp\php83F0.tmp' (length=27)
            'error' => int 0
           'size' => int 297749

**Comment by claviska** [comment]
You're using the temp name which doesn't have an extension. You need to specify an output format.

**Comment by w4r0** [comment]
Brilliant!

**Comment by mrhmansour** [comment]
I have the same problem, after uploading image to server (linux), fit_to_width throwing exception unsupported format ..

But it's an image (.jpg) !!
