### ISSUE TITLE
get filesize possible?

### ISSUE THREAD

**Issue by elburro1887** [claviska/SimpleImage#95]
Is there a way to get the file size of the image before it gets output?

This would be useful for example when setting the content-length value on my server, so that the client knows how big the file is going to be.

**Comment by claviska** [comment]
I don't think is reliably possible. The file size can vary widely depending on the format and compression rate. You'd have to write it to a temp file first to grab the size.






— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net

**Comment by elburro1887** [comment]
OK, this is what i thought.
Thanks!
