### ISSUE TITLE
Cannot redeclare class

### ISSUE THREAD

**Issue by green22sanjay** [claviska/SimpleImage#96]
Cannot redeclare class abeautifulsite\\SimpleImage in /var/www/html/abeautifulsite/SimpleImage.php

**Comment by mikedidomizio** [comment]
Without code it's hard to tell your issue.  Did you try Google?  My guess is that you're including the script twice into your script, which has the PHP class in it.

```php
include 'simpleImage.php';

include 'simpleImage.php'; // This would throw an error
```

**Comment by claviska** [comment]
Yep, you're most likely including the class twice. If you're using an autoloader and including it manually, that would also happen.
