### ISSUE TITLE
Can we check if $img->save(); was succesfull?

### ISSUE THREAD

**Issue by Wyzix33** [claviska/SimpleImage#99]
Hi, is there a way to be sure the image was saved?

something like : 

if($img->save()) {
   //insert file name into the database
   ....
} else {
   //something is wrong
   ....
}

or i have to relay on try catch to know that?

Thanks and keep up the good work

**Comment by claviska** [comment]
An [exception will be thrown](https://github.com/claviska/SimpleImage/blob/master/src/abeautifulsite/SimpleImage.php#L905) if the save fails.
